// ============================================================
// British English Grammar Tutor — Irregular Verbs (B1 level)
// ============================================================

export interface IrregularVerb {
  /** Base form (V1) */
  v1: string;
  /** Past Simple form (V2) */
  v2: string;
  /** Past Participle form (V3) */
  v3: string;
  /** Russian translation */
  ru: string;
}

/**
 * 87 irregular verbs for B1 level, sorted alphabetically by V1.
 * British English spelling is preferred where it differs from American.
 */
export const IRREGULAR_VERBS: IrregularVerb[] = [
  { v1: "arise", v2: "arose", v3: "arisen", ru: "возникать" },
  { v1: "awake", v2: "awoke", v3: "awoken", ru: "пробуждаться" },
  { v1: "be", v2: "was/were", v3: "been", ru: "быть" },
  { v1: "bear", v2: "bore", v3: "born/borne", ru: "родить/нести" },
  { v1: "beat", v2: "beat", v3: "beaten", ru: "бить" },
  { v1: "become", v2: "became", v3: "become", ru: "становиться" },
  { v1: "begin", v2: "began", v3: "begun", ru: "начинать" },
  { v1: "bend", v2: "bent", v3: "bent", ru: "гнуть" },
  { v1: "bet", v2: "bet", v3: "bet", ru: "держать пари" },
  { v1: "bind", v2: "bound", v3: "bound", ru: "связывать" },
  { v1: "bite", v2: "bit", v3: "bitten", ru: "кусать" },
  { v1: "bleed", v2: "bled", v3: "bled", ru: "кровоточить" },
  { v1: "blow", v2: "blew", v3: "blown", ru: "дуть" },
  { v1: "break", v2: "broke", v3: "broken", ru: "ломать" },
  { v1: "bring", v2: "brought", v3: "brought", ru: "приносить" },
  { v1: "build", v2: "built", v3: "built", ru: "строить" },
  { v1: "burn", v2: "burnt", v3: "burnt", ru: "гореть" },
  { v1: "buy", v2: "bought", v3: "bought", ru: "покупать" },
  { v1: "catch", v2: "caught", v3: "caught", ru: "ловить" },
  { v1: "choose", v2: "chose", v3: "chosen", ru: "выбирать" },
  { v1: "come", v2: "came", v3: "come", ru: "приходить" },
  { v1: "cost", v2: "cost", v3: "cost", ru: "стоить" },
  { v1: "cut", v2: "cut", v3: "cut", ru: "резать" },
  { v1: "deal", v2: "dealt", v3: "dealt", ru: "иметь дело" },
  { v1: "dig", v2: "dug", v3: "dug", ru: "копать" },
  { v1: "do", v2: "did", v3: "done", ru: "делать" },
  { v1: "draw", v2: "drew", v3: "drawn", ru: "рисовать" },
  { v1: "dream", v2: "dreamt", v3: "dreamt", ru: "мечтать/сниться" },
  { v1: "drink", v2: "drank", v3: "drunk", ru: "пить" },
  { v1: "drive", v2: "drove", v3: "driven", ru: "водить" },
  { v1: "eat", v2: "ate", v3: "eaten", ru: "есть" },
  { v1: "fall", v2: "fell", v3: "fallen", ru: "падать" },
  { v1: "feed", v2: "fed", v3: "fed", ru: "кормить" },
  { v1: "feel", v2: "felt", v3: "felt", ru: "чувствовать" },
  { v1: "fight", v2: "fought", v3: "fought", ru: "бороться" },
  { v1: "find", v2: "found", v3: "found", ru: "находить" },
  { v1: "fly", v2: "flew", v3: "flown", ru: "летать" },
  { v1: "forget", v2: "forgot", v3: "forgotten", ru: "забывать" },
  { v1: "forgive", v2: "forgave", v3: "forgiven", ru: "прощать" },
  { v1: "freeze", v2: "froze", v3: "frozen", ru: "замерзать" },
  { v1: "get", v2: "got", v3: "got", ru: "получать" },
  { v1: "give", v2: "gave", v3: "given", ru: "давать" },
  { v1: "go", v2: "went", v3: "gone", ru: "идти" },
  { v1: "grow", v2: "grew", v3: "grown", ru: "расти" },
  { v1: "hang", v2: "hung", v3: "hung", ru: "висеть" },
  { v1: "have", v2: "had", v3: "had", ru: "иметь" },
  { v1: "hear", v2: "heard", v3: "heard", ru: "слышать" },
  { v1: "hide", v2: "hid", v3: "hidden", ru: "прятать" },
  { v1: "hit", v2: "hit", v3: "hit", ru: "ударять" },
  { v1: "hold", v2: "held", v3: "held", ru: "держать" },
  { v1: "hurt", v2: "hurt", v3: "hurt", ru: "ранить" },
  { v1: "keep", v2: "kept", v3: "kept", ru: "хранить" },
  { v1: "know", v2: "knew", v3: "known", ru: "знать" },
  { v1: "lay", v2: "laid", v3: "laid", ru: "класть" },
  { v1: "lead", v2: "led", v3: "led", ru: "вести" },
  { v1: "leave", v2: "left", v3: "left", ru: "уходить" },
  { v1: "lend", v2: "lent", v3: "lent", ru: "одалживать" },
  { v1: "let", v2: "let", v3: "let", ru: "позволять" },
  { v1: "lie", v2: "lay", v3: "lain", ru: "лежать" },
  { v1: "lose", v2: "lost", v3: "lost", ru: "терять" },
  { v1: "make", v2: "made", v3: "made", ru: "делать" },
  { v1: "mean", v2: "meant", v3: "meant", ru: "означать" },
  { v1: "meet", v2: "met", v3: "met", ru: "встречать" },
  { v1: "pay", v2: "paid", v3: "paid", ru: "платить" },
  { v1: "put", v2: "put", v3: "put", ru: "класть" },
  { v1: "read", v2: "read", v3: "read", ru: "читать" },
  { v1: "ride", v2: "rode", v3: "ridden", ru: "ездить верхом" },
  { v1: "ring", v2: "rang", v3: "rung", ru: "звонить" },
  { v1: "rise", v2: "rose", v3: "risen", ru: "вставать" },
  { v1: "run", v2: "ran", v3: "run", ru: "бежать" },
  { v1: "say", v2: "said", v3: "said", ru: "говорить" },
  { v1: "see", v2: "saw", v3: "seen", ru: "видеть" },
  { v1: "sell", v2: "sold", v3: "sold", ru: "продавать" },
  { v1: "send", v2: "sent", v3: "sent", ru: "отправлять" },
  { v1: "set", v2: "set", v3: "set", ru: "устанавливать" },
  { v1: "shake", v2: "shook", v3: "shaken", ru: "трясти" },
  { v1: "shine", v2: "shone", v3: "shone", ru: "светить" },
  { v1: "shoot", v2: "shot", v3: "shot", ru: "стрелять" },
  { v1: "show", v2: "showed", v3: "shown", ru: "показывать" },
  { v1: "shut", v2: "shut", v3: "shut", ru: "закрывать" },
  { v1: "sing", v2: "sang", v3: "sung", ru: "петь" },
  { v1: "sink", v2: "sank", v3: "sunk", ru: "тонуть" },
  { v1: "sit", v2: "sat", v3: "sat", ru: "сидеть" },
  { v1: "sleep", v2: "slept", v3: "slept", ru: "спать" },
  { v1: "slide", v2: "slid", v3: "slid", ru: "скользить" },
  { v1: "speak", v2: "spoke", v3: "spoken", ru: "говорить" },
  { v1: "spend", v2: "spent", v3: "spent", ru: "тратить" },
  { v1: "stand", v2: "stood", v3: "stood", ru: "стоять" },
  { v1: "steal", v2: "stole", v3: "stolen", ru: "красть" },
  { v1: "swim", v2: "swam", v3: "swum", ru: "плавать" },
  { v1: "take", v2: "took", v3: "taken", ru: "брать" },
  { v1: "teach", v2: "taught", v3: "taught", ru: "учить" },
  { v1: "tear", v2: "tore", v3: "torn", ru: "рвать" },
  { v1: "tell", v2: "told", v3: "told", ru: "рассказывать" },
  { v1: "think", v2: "thought", v3: "thought", ru: "думать" },
  { v1: "throw", v2: "threw", v3: "thrown", ru: "бросать" },
  { v1: "understand", v2: "understood", v3: "understood", ru: "понимать" },
  { v1: "wake", v2: "woke", v3: "woken", ru: "просыпаться" },
  { v1: "wear", v2: "wore", v3: "worn", ru: "носить" },
  { v1: "win", v2: "won", v3: "won", ru: "выигрывать" },
  { v1: "write", v2: "wrote", v3: "written", ru: "писать" },
];
