import type { Exercise } from "@/lib/tutor-data";

// ============================================================
// Future Continuous — 100 exercises
// ============================================================

export const futureContinuousExercises: Exercise[] = [
  // ===== Multiple Choice (1–35) =====

  // Basic affirmative form — will be + V-ing
  { id: 1, tense: "future-continuous", type: "multiple_choice", question: "At 6 pm tomorrow, I ___ dinner.", options: ["will be cooking", "will cook", "am cooking", "cook"], correctAnswer: "will be cooking", explanation: "Future Continuous: will be + V-ing. Действие будет в процессе в определённый момент в будущем (at 6 pm tomorrow).", hintIds: ["ftc-formula", "ftc-usage-process"] },
  { id: 2, tense: "future-continuous", type: "multiple_choice", question: "This time next week, we ___ to Paris.", options: ["will be flying", "will fly", "are flying", "fly"], correctAnswer: "will be flying", explanation: "This time next week — сигнал Future Continuous. Действие будет в процессе: will be flying.", hintIds: ["ftc-formula", "ftc-signal-at-time"] },
  { id: 3, tense: "future-continuous", type: "multiple_choice", question: "She ___ on her project all afternoon tomorrow.", options: ["will be working", "will work", "is working", "works"], correctAnswer: "will be working", explanation: "All afternoon tomorrow — сигнал Future Continuous. Действие будет длиться: will be working.", hintIds: ["ftc-formula", "ftc-signal-all-day"] },
  { id: 4, tense: "future-continuous", type: "multiple_choice", question: "Tomorrow morning, they ___ the house.", options: ["will be painting", "will paint", "are painting", "paint"], correctAnswer: "will be painting", explanation: "Tomorrow morning — действие будет в процессе. Future Continuous: will be painting.", hintIds: ["ftc-formula", "ftc-signal-all-day"] },
  { id: 5, tense: "future-continuous", type: "multiple_choice", question: "He ___ the report between 2 and 4 pm tomorrow.", options: ["will be writing", "will write", "writes", "is writing"], correctAnswer: "will be writing", explanation: "Between 2 and 4 pm — указание промежутка времени. Future Continuous: will be writing.", hintIds: ["ftc-formula", "ftc-signal-from-to"] },

  // Negative form — won't be + V-ing
  { id: 6, tense: "future-continuous", type: "multiple_choice", question: "I ___ TV at 8 pm. I'll be studying.", options: ["won't be watching", "won't watch", "don't watch", "am not watching"], correctAnswer: "won't be watching", explanation: "Won't be + V-ing — отрицание Future Continuous. Действие НЕ будет в процессе.", hintIds: ["ftc-negative", "ftc-usage-process"] },
  { id: 7, tense: "future-continuous", type: "multiple_choice", question: "They ___ football tomorrow evening. They have other plans.", options: ["won't be playing", "won't play", "don't play", "aren't playing"], correctAnswer: "won't be playing", explanation: "Won't be playing — действие НЕ будет в процессе в указанное время.", hintIds: ["ftc-negative", "ftc-signal-at-time"] },
  { id: 8, tense: "future-continuous", type: "multiple_choice", question: "She ___ us at the station. She'll be at work.", options: ["won't be meeting", "won't meet", "isn't meeting", "doesn't meet"], correctAnswer: "won't be meeting", explanation: "Won't be meeting — она НЕ будет в процессе встречи. Причина: будет на работе.", hintIds: ["ftc-negative", "ftc-usage-process"] },
  { id: 9, tense: "future-continuous", type: "multiple_choice", question: "We ___ any guests next weekend. The house will be empty.", options: ["won't be having", "won't have", "aren't having", "don't have"], correctAnswer: "won't be having", explanation: "Won't be having — не будет принимания гостей в процессе. Have здесь = действие (приём гостей).", hintIds: ["ftc-negative", "ftc-dual-have"] },
  { id: 10, tense: "future-continuous", type: "multiple_choice", question: "He ___ the car tomorrow. He's taking the bus.", options: ["won't be using", "won't use", "isn't using", "doesn't use"], correctAnswer: "won't be using", explanation: "Won't be using — он НЕ будет использовать машину в это время.", hintIds: ["ftc-negative", "ftc-wont-be"] },

  // Questions — Will + subject + be + V-ing?
  { id: 11, tense: "future-continuous", type: "multiple_choice", question: "___ you ___ anything at 5 pm tomorrow?", options: ["Will / be doing", "Will / do", "Do / do", "Are / doing"], correctAnswer: "Will / be doing", explanation: "Вопрос в Future Continuous: Will + you + be + V-ing?", hintIds: ["ftc-question", "ftc-signal-at-time"] },
  { id: 12, tense: "future-continuous", type: "multiple_choice", question: "___ she ___ the kids to school tomorrow morning?", options: ["Will / be taking", "Will / take", "Does / take", "Is / taking"], correctAnswer: "Will / be taking", explanation: "Вопрос в Future Continuous: Will + she + be + V-ing? Уточнение плана на утро.", hintIds: ["ftc-question", "ftc-signal-at-time"] },
  { id: 13, tense: "future-continuous", type: "multiple_choice", question: "___ they ___ the meeting this afternoon?", options: ["Will / be attending", "Will / attend", "Do / attend", "Are / attending"], correctAnswer: "Will / be attending", explanation: "Вопрос: будут ли они в процессе участия во встрече?", hintIds: ["ftc-question", "ftc-usage-process"] },
  { id: 14, tense: "future-continuous", type: "multiple_choice", question: "___ we ___ a test this time tomorrow?", options: ["Will / be having", "Will / have", "Do / have", "Are / having"], correctAnswer: "Will / be having", explanation: "This time tomorrow — сигнал FC. Will we be having a test?", hintIds: ["ftc-question", "ftc-signal-at-time"] },

  // Wh-questions — Wh- + will + subject + be + V-ing?
  { id: 15, tense: "future-continuous", type: "multiple_choice", question: "What ___ you ___ at 9 am tomorrow?", options: ["will / be doing", "will / do", "do / do", "are / doing"], correctAnswer: "will / be doing", explanation: "Wh-вопрос в Future Continuous: What + will + you + be + V-ing?", hintIds: ["ftc-wh-question", "ftc-signal-at-time"] },
  { id: 16, tense: "future-continuous", type: "multiple_choice", question: "Where ___ he ___ at this time next week?", options: ["will / be staying", "will / stay", "does / stay", "is / staying"], correctAnswer: "will / be staying", explanation: "This time next week — FC. Where will he be staying?", hintIds: ["ftc-wh-question", "ftc-signal-at-time"] },
  { id: 17, tense: "future-continuous", type: "multiple_choice", question: "Who ___ you ___ with at the party next Saturday?", options: ["will / be dancing", "will / dance", "do / dance", "are / dancing"], correctAnswer: "will / be dancing", explanation: "Wh-вопрос в Future Continuous: Who will you be dancing with?", hintIds: ["ftc-wh-question", "ftc-usage-process"] },
  { id: 18, tense: "future-continuous", type: "multiple_choice", question: "How long ___ she ___ for the exam next month?", options: ["will / be preparing", "will / prepare", "does / prepare", "is / preparing"], correctAnswer: "will / be preparing", explanation: "How long — уточнение длительности процесса: will be preparing.", hintIds: ["ftc-wh-question", "ftc-signal-all-day"] },

  // Polite inquiries — Will you be + V-ing?
  { id: 19, tense: "future-continuous", type: "multiple_choice", question: "___ you ___ lunch when I call?", options: ["Will / be having", "Will / have", "Do / have", "Are / having"], correctAnswer: "Will / be having", explanation: "Will you be having lunch? — вежливый вопрос о планах, чтобы не помешать.", hintIds: ["ftc-polite-questions", "ftc-usage-polite"] },
  { id: 20, tense: "future-continuous", type: "multiple_choice", question: "___ you ___ the library this afternoon? I need a book.", options: ["Will / be using", "Will / use", "Do / use", "Are / using"], correctAnswer: "Will / be using", explanation: "Will you be using the library? — вежливый вопрос: будешь ли ты пользоваться библиотекой?", hintIds: ["ftc-polite-questions", "ftc-usage-polite"] },
  { id: 21, tense: "future-continuous", type: "multiple_choice", question: "___ you ___ near the post office later? Could you post this letter?", options: ["Will / be passing", "Will / pass", "Do / pass", "Are / passing"], correctAnswer: "Will / be passing", explanation: "Will you be passing near...? — вежливая просьба, которая не выглядит давлением.", hintIds: ["ftc-polite-questions", "ftc-usage-polite"] },
  { id: 22, tense: "future-continuous", type: "multiple_choice", question: "___ you ___ home early tonight? I'd like to discuss something.", options: ["Will / be coming", "Will / come", "Do / come", "Are / coming"], correctAnswer: "Will / be coming", explanation: "Will you be coming home early? — вежливый вопрос о планах без давления.", hintIds: ["ftc-polite-questions", "ftc-usage-polite"] },

  // Parallel actions — while + Future Continuous
  { id: 23, tense: "future-continuous", type: "multiple_choice", question: "While I ___ dinner, he ___ the living room.", options: ["will be cooking / will be tidying", "cook / tidies", "am cooking / will tidy", "will cook / tidies"], correctAnswer: "will be cooking / will be tidying", explanation: "While + Future Continuous — два параллельных будущих действия: will be cooking / will be tidying.", hintIds: ["ftc-usage-parallel", "ftc-signal-while"] },
  { id: 24, tense: "future-continuous", type: "multiple_choice", question: "Tomorrow morning, she ___ on the train while he ___.", options: ["will be reading / will be sleeping", "reads / sleeps", "will read / sleeps", "is reading / is sleeping"], correctAnswer: "will be reading / will be sleeping", explanation: "Два параллельных действия: while + Future Continuous для обоих.", hintIds: ["ftc-usage-parallel", "ftc-signal-while"] },

  // Background action — when + Future Continuous
  { id: 25, tense: "future-continuous", type: "multiple_choice", question: "When I arrive, they ___ lunch.", options: ["will be having", "will have", "are having", "have"], correctAnswer: "will be having", explanation: "When I arrive — фон, на котором произойдёт действие. FC: will be having.", hintIds: ["ftc-usage-background", "ftc-signal-when"] },
  { id: 26, tense: "future-continuous", type: "multiple_choice", question: "Please call me when you ___ the report. I want to check it.", options: ["will be finishing", "will finish", "finish", "are finishing"], correctAnswer: "will be finishing", explanation: "Will be finishing — фон для просьбы позвонить. Действие будет в процессе завершения.", hintIds: ["ftc-usage-background", "ftc-signal-when"] },

  // FC vs Future Simple comparison
  { id: 27, tense: "future-continuous", type: "multiple_choice", question: "I ___ the exam. I have already registered. (intention)", options: ["will take", "will be taking", "am going to take", "take"], correctAnswer: "will take", explanation: "Future Simple — факт / намерение: I will take the exam. НЕ процесс.", hintIds: ["ftc-vs-future-simple", "ftc-usage-expected"] },
  { id: 28, tense: "future-continuous", type: "multiple_choice", question: "This time tomorrow, I ___ the exam. (in progress)", options: ["will be taking", "will take", "take", "am taking"], correctAnswer: "will be taking", explanation: "This time tomorrow — действие в процессе → Future Continuous: will be taking.", hintIds: ["ftc-vs-future-simple", "ftc-usage-process"] },
  { id: 29, tense: "future-continuous", type: "multiple_choice", question: "She ___ a letter to her grandmother every Sunday. (routine)", options: ["will write", "will be writing", "writes", "is writing"], correctAnswer: "will write", explanation: "Регулярное действие (every Sunday) — Future Simple: will write. НЕ Future Continuous.", hintIds: ["ftc-vs-future-simple", "ftc-usage-expected"] },

  // FC vs Present Continuous comparison
  { id: 30, tense: "future-continuous", type: "multiple_choice", question: "We ___ to Madrid next month. The flights are already booked. (arranged)", options: ["are flying", "will be flying", "will fly", "fly"], correctAnswer: "are flying", explanation: "Договорённость (flights booked) → Present Continuous: are flying, НЕ Future Continuous.", hintIds: ["ftc-vs-present-continuous", "ftc-usage-expected"] },
  { id: 31, tense: "future-continuous", type: "multiple_choice", question: "At noon tomorrow, we ___ over the Atlantic. (in progress, no specific arrangement)", options: ["will be flying", "are flying", "will fly", "fly"], correctAnswer: "will be flying", explanation: "Действие будет в процессе в определённый момент → Future Continuous: will be flying.", hintIds: ["ftc-vs-present-continuous", "ftc-usage-process"] },
  { id: 32, tense: "future-continuous", type: "multiple_choice", question: "I ___ the doctor on Tuesday at 3 pm. I made the appointment. (arranged)", options: ["am seeing", "will be seeing", "will see", "see"], correctAnswer: "am seeing", explanation: "Договорённость (made appointment) → Present Continuous: am seeing. НЕ Future Continuous.", hintIds: ["ftc-vs-present-continuous", "ftc-usage-expected"] },

  // Stative verbs — NOT used in Future Continuous
  { id: 33, tense: "future-continuous", type: "multiple_choice", question: "I ___ the answer by tomorrow. (NOT: will be knowing)", options: ["will know", "will be knowing", "know", "am knowing"], correctAnswer: "will know", explanation: "Know — стативный глагол, НЕ используется в Continuous. Future Simple: will know.", hintIds: ["ftc-stative", "ftc-stative-list"] },
  { id: 34, tense: "future-continuous", type: "multiple_choice", question: "She ___ the film by next Friday. She loves thrillers. (opinion)", options: ["will think it is great", "will be thinking it is great", "thinks", "is thinking"], correctAnswer: "will think it is great", explanation: "Think как мнение — стативный глагол. Future Simple: will think. НЕ will be thinking.", hintIds: ["ftc-dual-think", "ftc-stative"] },
  { id: 35, tense: "future-continuous", type: "multiple_choice", question: "This time next week, he ___ about the problem. (reflecting)", options: ["will be thinking", "will think", "thinks", "is thinking"], correctAnswer: "will be thinking", explanation: "Think как размышление = процесс → CAN use Future Continuous: will be thinking.", hintIds: ["ftc-dual-think", "ftc-usage-process"] },

  // ===== Fill in the Blank (36–65) =====

  // Affirmative — will be + V-ing
  { id: 36, tense: "future-continuous", type: "fill_blank", question: "At 8 pm tonight, she ___ (watch) a documentary on TV.", correctAnswer: "will be watching", explanation: "Future Continuous: will be + V-ing. Действие будет в процессе в 8 вечера.", hintIds: ["ftc-formula", "ftc-usage-process"] },
  { id: 37, tense: "future-continuous", type: "fill_blank", question: "This time tomorrow, we ___ (travel) to Scotland by train.", correctAnswer: "will be travelling", explanation: "This time tomorrow — сигнал FC. Будем в процессе поездки: will be travelling.", hintIds: ["ftc-formula", "ftc-signal-at-time"] },
  { id: 38, tense: "future-continuous", type: "fill_blank", question: "He ___ (study) for his exams all day Saturday.", correctAnswer: "will be studying", explanation: "All day Saturday — сигнал Future Continuous: will be studying.", hintIds: ["ftc-formula", "ftc-signal-all-day"] },
  { id: 39, tense: "future-continuous", type: "fill_blank", question: "Tomorrow from 10 to 12, I ___ (attend) a conference.", correctAnswer: "will be attending", explanation: "From 10 to 12 — промежуток времени → Future Continuous: will be attending.", hintIds: ["ftc-formula", "ftc-signal-from-to"] },
  { id: 40, tense: "future-continuous", type: "fill_blank", question: "During the lesson, the students ___ (take) notes.", correctAnswer: "will be taking", explanation: "During the lesson — действие в процессе → will be taking notes.", hintIds: ["ftc-formula", "ftc-signal-from-to"] },

  // Negative — won't be + V-ing
  { id: 41, tense: "future-continuous", type: "fill_blank", question: "I ___ (not / sleep) at midnight. I'll be working.", correctAnswer: "won't be sleeping", explanation: "Won't be + V-ing: не буду спать (в процессе) — буду работать.", hintIds: ["ftc-negative", "ftc-usage-process"] },
  { id: 42, tense: "future-continuous", type: "fill_blank", question: "They ___ (not / play) tennis at 4 pm. They'll be at the dentist.", correctAnswer: "won't be playing", explanation: "Won't be playing — они НЕ будут в процессе игры в теннис.", hintIds: ["ftc-negative", "ftc-signal-at-time"] },
  { id: 43, tense: "future-continuous", type: "fill_blank", question: "She ___ (not / drive) to work tomorrow. She'll cycle instead.", correctAnswer: "won't be driving", explanation: "Won't be driving — она НЕ будет ехать на машине (в процессе).", hintIds: ["ftc-negative", "ftc-wont-be"] },
  { id: 44, tense: "future-continuous", type: "fill_blank", question: "We ___ (not / stay) at the hotel next week. We're camping.", correctAnswer: "won't be staying", explanation: "Won't be staying — мы НЕ будем проживать в отеле.", hintIds: ["ftc-negative", "ftc-usage-process"] },
  { id: 45, tense: "future-continuous", type: "fill_blank", question: "The children ___ (not / watch) TV all evening. They need to do homework.", correctAnswer: "won't be watching", explanation: "Won't be watching — дети НЕ будут смотреть телевизор весь вечер.", hintIds: ["ftc-negative", "ftc-signal-all-day"] },

  // Questions — Will + subject + be + V-ing?
  { id: 46, tense: "future-continuous", type: "fill_blank", question: "___ (you / use) the car this afternoon?", correctAnswer: "Will you be using", explanation: "Will you be using? — вежливый вопрос о планах на машину.", hintIds: ["ftc-question", "ftc-polite-questions"] },
  { id: 47, tense: "future-continuous", type: "fill_blank", question: "___ (she / be) working at 10 pm tonight?", correctAnswer: "Will she be", explanation: "Вопрос в Future Continuous: Will + she + be + V-ing?", hintIds: ["ftc-question", "ftc-signal-at-time"] },
  { id: 48, tense: "future-continuous", type: "fill_blank", question: "___ (they / wait) for us at the station when we arrive?", correctAnswer: "Will they be waiting", explanation: "Will they be waiting? — будут ли они ждать нас (в процессе).", hintIds: ["ftc-question", "ftc-usage-background"] },
  { id: 49, tense: "future-continuous", type: "fill_blank", question: "___ (the baby / sleep) when we get home?", correctAnswer: "Will the baby be sleeping", explanation: "Will the baby be sleeping? — вежливый вопрос: будет ли малыш спать?", hintIds: ["ftc-question", "ftc-usage-background"] },
  { id: 50, tense: "future-continuous", type: "fill_blank", question: "___ (it / rain) when we reach the coast, do you think?", correctAnswer: "Will it be raining", explanation: "Will it be raining? — вопрос о действии в процессе в будущем моменте.", hintIds: ["ftc-question", "ftc-usage-process"] },

  // Wh-questions
  { id: 51, tense: "future-continuous", type: "fill_blank", question: "What ___ (you / be doing) this time tomorrow?", correctAnswer: "will you be doing", explanation: "What + will + you + be + V-ing? Wh-вопрос в Future Continuous.", hintIds: ["ftc-wh-question", "ftc-signal-at-time"] },
  { id: 52, tense: "future-continuous", type: "fill_blank", question: "Where ___ (they / be staying) during their holiday?", correctAnswer: "will they be staying", explanation: "Where + will + they + be + V-ing? Уточнение места пребывания.", hintIds: ["ftc-wh-question", "ftc-signal-from-to"] },
  { id: 53, tense: "future-continuous", type: "fill_blank", question: "Who ___ (be performing) at the concert next Friday?", correctAnswer: "will be performing", explanation: "Who + will + be + V-ing? Кто будет выступать (в процессе)?", hintIds: ["ftc-wh-question", "ftc-usage-process"] },

  // Signal words: while, when, all day
  { id: 54, tense: "future-continuous", type: "fill_blank", question: "While you ___ (cook) dinner, I ___ (set) the table.", correctAnswer: "will be cooking / will be setting", explanation: "While + Future Continuous — два параллельных будущих действия.", hintIds: ["ftc-signal-while", "ftc-usage-parallel"] },
  { id: 55, tense: "future-continuous", type: "fill_blank", question: "When I ___ (get) home tonight, my parents ___ (have) dinner.", correctAnswer: "get / will be having", explanation: "When + Present Simple (придаточное), главное: will be having (фон).", hintIds: ["ftc-signal-when", "ftc-time-clauses"] },
  { id: 56, tense: "future-continuous", type: "fill_blank", question: "She ___ (be gardening) all morning tomorrow.", correctAnswer: "will be gardening", explanation: "All morning tomorrow — сигнал FC: will be gardening.", hintIds: ["ftc-signal-all-day", "ftc-usage-process"] },
  { id: 57, tense: "future-continuous", type: "fill_blank", question: "During the flight, we ___ (watch) films.", correctAnswer: "will be watching", explanation: "During the flight — действие будет в процессе на протяжении полёта.", hintIds: ["ftc-signal-from-to", "ftc-usage-process"] },

  // Expected / inevitable actions
  { id: 58, tense: "future-continuous", type: "fill_blank", question: "In a few years, self-driving cars ___ (be transporting) people everywhere.", correctAnswer: "will be transporting", explanation: "Ожидаемое / неизбежное действие в будущем → Future Continuous: will be transporting.", hintIds: ["ftc-usage-expected", "ftc-usage-process"] },
  { id: 59, tense: "future-continuous", type: "fill_blank", question: "The band ___ (be playing) at Wembley Stadium next summer.", correctAnswer: "will be playing", explanation: "Запланированное действие, ожидаемое в будущем: will be playing.", hintIds: ["ftc-usage-expected", "ftc-usage-process"] },

  // Spelling rules
  { id: 60, tense: "future-continuous", type: "fill_blank", question: "Tomorrow at 9, she ___ (have) breakfast.", correctAnswer: "will be having", explanation: "Will be having. НЕ will be being — глагол have используется как действие (завтракать).", hintIds: ["ftc-no-double-be", "ftc-dual-have"] },
  { id: 61, tense: "future-continuous", type: "fill_blank", question: "He ___ (lie) on the beach this time tomorrow.", correctAnswer: "will be lying", explanation: "Правописание: lie → lying (убираем -e, добавляем -ing). Will be lying.", hintIds: ["ftc-spelling-drop-e", "ftc-signal-at-time"] },
  { id: 62, tense: "future-continuous", type: "fill_blank", question: "They ___ (run) a marathon this time next week.", correctAnswer: "will be running", explanation: "Правописание: run → running (удваиваем согласную -n-). Will be running.", hintIds: ["ftc-spelling-double", "ftc-signal-at-time"] },
  { id: 63, tense: "future-continuous", type: "fill_blank", question: "She ___ (die) her hair tomorrow afternoon.", correctAnswer: "will be dying", explanation: "Правописание: die → dying (-ie → -y + -ing). Will be dying.", hintIds: ["ftc-spelling-ie", "ftc-usage-process"] },

  // FC vs FS comparison
  { id: 64, tense: "future-continuous", type: "fill_blank", question: "This time tomorrow, I ___ (drive) to Birmingham. (process)", correctAnswer: "will be driving", explanation: "This time tomorrow — действие в процессе → will be driving.", hintIds: ["ftc-vs-future-simple", "ftc-usage-process"] },
  { id: 65, tense: "future-continuous", type: "fill_blank", question: "I ___ (drive) to Birmingham tomorrow. (fact, the whole journey)", correctAnswer: "will drive", explanation: "Факт / общий результат поездки → Future Simple: will drive. НЕ will be driving.", hintIds: ["ftc-vs-future-simple", "ftc-usage-expected"] },

  // ===== Translate RU → EN (66–100) =====

  // Process at a specific moment
  { id: 66, tense: "future-continuous", type: "translate_ru_en", question: "Завтра в 6 вечера я буду готовить ужин.", correctAnswer: "I will be cooking dinner at 6 pm tomorrow", explanation: "В определённый момент (at 6 pm) действие будет в процессе → will be cooking.", hintIds: ["ftc-formula", "ftc-usage-process"] },
  { id: 67, tense: "future-continuous", type: "translate_ru_en", question: "В это время завтра мы будем лететь над океаном.", correctAnswer: "We will be flying over the ocean this time tomorrow", explanation: "This time tomorrow — сигнал Future Continuous: will be flying.", hintIds: ["ftc-signal-at-time", "ftc-usage-process"] },
  { id: 68, tense: "future-continuous", type: "translate_ru_en", question: "Завтра с 10 до 12 она будет писать эссе.", correctAnswer: "She will be writing an essay from 10 to 12 tomorrow", explanation: "From 10 to 12 — промежуток времени → will be writing.", hintIds: ["ftc-signal-from-to", "ftc-usage-process"] },
  { id: 69, tense: "future-continuous", type: "translate_ru_en", question: "Он будет работать в саду всё утро в субботу.", correctAnswer: "He will be working in the garden all morning on Saturday", explanation: "All morning — сигнал Future Continuous: will be working.", hintIds: ["ftc-signal-all-day", "ftc-usage-process"] },
  { id: 70, tense: "future-continuous", type: "translate_ru_en", question: "Во время экзамена студенты будут писать тест.", correctAnswer: "During the exam the students will be taking the test", explanation: "During — действие в процессе → will be taking the test.", hintIds: ["ftc-signal-from-to", "ftc-usage-process"] },

  // Background for another action
  { id: 71, tense: "future-continuous", type: "translate_ru_en", question: "Когда я приду домой, семья будет ужинать.", correctAnswer: "When I come home, my family will be having dinner", explanation: "When + Present Simple, главное: will be having (фон для прихода).", hintIds: ["ftc-usage-background", "ftc-signal-when"] },
  { id: 72, tense: "future-continuous", type: "translate_ru_en", question: "Когда ты позвонишь, я буду принимать ванну.", correctAnswer: "When you call, I will be having a bath", explanation: "When + Present Simple, главное: will be having a bath (фон).", hintIds: ["ftc-usage-background", "ftc-signal-when"] },
  { id: 73, tense: "future-continuous", type: "translate_ru_en", question: "Когда мы доберёмся до театра, спектакль уже будет идти.", correctAnswer: "When we get to the theatre, the play will already be starting", explanation: "Фон для другого будущего действия: the play will be starting.", hintIds: ["ftc-usage-background", "ftc-time-clauses"] },

  // Parallel actions
  { id: 74, tense: "future-continuous", type: "translate_ru_en", question: "Пока ты будешь убирать комнату, я буду мыть посуду.", correctAnswer: "While you are tidying the room, I will be washing the dishes", explanation: "Параллельные действия: while + Present Continuous, главное — Future Continuous.", hintIds: ["ftc-usage-parallel", "ftc-signal-while"] },
  { id: 75, tense: "future-continuous", type: "translate_ru_en", question: "Завтра утром она будет читать газету, а он будет слушать радио.", correctAnswer: "Tomorrow morning she will be reading the newspaper and he will be listening to the radio", explanation: "Два параллельных будущих действия → оба в Future Continuous.", hintIds: ["ftc-usage-parallel", "ftc-signal-all-day"] },
  { id: 76, tense: "future-continuous", type: "translate_ru_en", question: "Пока дети будут играть в парке, мы будем пить кофе.", correctAnswer: "While the children are playing in the park, we will be having coffee", explanation: "While + Present Continuous, главное — Future Continuous (параллельные действия).", hintIds: ["ftc-usage-parallel", "ftc-signal-while"] },

  // Polite questions about plans
  { id: 77, tense: "future-continuous", type: "translate_ru_en", question: "Ты будешь использовать машину сегодня вечером? (вежливый вопрос)", correctAnswer: "Will you be using the car this evening", explanation: "Will you be using? — вежливый вопрос о планах, без давления.", hintIds: ["ftc-polite-questions", "ftc-usage-polite"] },
  { id: 78, tense: "future-continuous", type: "translate_ru_en", question: "Вы будете проходить мимо магазина? Можешь купить хлеб?", correctAnswer: "Will you be passing by the shop? Can you buy some bread?", explanation: "Will you be passing? — вежливый вопрос для ненавязчивой просьбы.", hintIds: ["ftc-polite-questions", "ftc-usage-polite"] },
  { id: 79, tense: "future-continuous", type: "translate_ru_en", question: "Вы будете обедать, когда я приду?", correctAnswer: "Will you be having lunch when I arrive", explanation: "Will you be having lunch? — вежливый вопрос: хотите ли вы, чтобы я не мешал?", hintIds: ["ftc-polite-questions", "ftc-usage-polite"] },

  // Expected / inevitable actions
  { id: 80, tense: "future-continuous", type: "translate_ru_en", question: "Через несколько лет роботы будут выполнять большинство домашних дел.", correctAnswer: "In a few years robots will be doing most household chores", explanation: "Ожидаемое развитие событий → Future Continuous: will be doing.", hintIds: ["ftc-usage-expected", "ftc-usage-process"] },
  { id: 81, tense: "future-continuous", type: "translate_ru_en", question: "В следующем месяце они будут ремонтировать нашу дорогу.", correctAnswer: "Next month they will be repairing our road", explanation: "Ожидаемое / запланированное действие → will be repairing.", hintIds: ["ftc-usage-expected", "ftc-usage-process"] },
  { id: 82, tense: "future-continuous", type: "translate_ru_en", question: "Завтра ночью будет идти снег.", correctAnswer: "It will be snowing tomorrow night", explanation: "Естественный процесс, ожидаемый в будущем → will be snowing.", hintIds: ["ftc-usage-expected", "ftc-usage-process"] },

  // Negative sentences
  { id: 83, tense: "future-continuous", type: "translate_ru_en", question: "Завтра в 7 вечера я не буду смотреть телевизор. Я буду заниматься.", correctAnswer: "I won't be watching TV at 7 pm tomorrow. I will be studying", explanation: "Won't be watching — действие НЕ будет в процессе.", hintIds: ["ftc-negative", "ftc-usage-process"] },
  { id: 84, tense: "future-continuous", type: "translate_ru_en", question: "Они не будут играть в футбол завтра. Они будут тренироваться.", correctAnswer: "They won't be playing football tomorrow. They will be training", explanation: "Won't be playing — НЕ будут в процессе игры.", hintIds: ["ftc-negative", "ftc-usage-process"] },
  { id: 85, tense: "future-continuous", type: "translate_ru_en", question: "Она не будет работать на следующей неделе. Она будет в отпуске.", correctAnswer: "She won't be working next week. She will be on holiday", explanation: "Won't be working — она НЕ будет в процессе работы.", hintIds: ["ftc-negative", "ftc-wont-be"] },

  // FC vs Future Simple comparisons
  { id: 86, tense: "future-continuous", type: "translate_ru_en", question: "Завтра в это время я буду сдавать экзамен. (в процессе)", correctAnswer: "I will be taking an exam this time tomorrow", explanation: "Действие в процессе → Future Continuous: will be taking.", hintIds: ["ftc-vs-future-simple", "ftc-usage-process"] },
  { id: 87, tense: "future-continuous", type: "translate_ru_en", question: "Я сдам экзамен завтра. (факт / результат)", correctAnswer: "I will pass the exam tomorrow", explanation: "Факт / результат → Future Simple: will pass. НЕ will be passing.", hintIds: ["ftc-vs-future-simple", "ftc-usage-expected"] },
  { id: 88, tense: "future-continuous", type: "translate_ru_en", question: "Завтра я поеду в Лондон на поезде. (факт / решение)", correctAnswer: "I will go to London by train tomorrow", explanation: "Решение / факт поездки → Future Simple: will go.", hintIds: ["ftc-vs-future-simple", "ftc-usage-expected"] },
  { id: 89, tense: "future-continuous", type: "translate_ru_en", question: "Завтра в 2 часа дня я буду ехать в Лондон на поезде. (в процессе)", correctAnswer: "I will be travelling to London by train at 2 pm tomorrow", explanation: "Действие в процессе → Future Continuous: will be travelling.", hintIds: ["ftc-vs-future-simple", "ftc-usage-process"] },

  // FC vs Present Continuous comparisons
  { id: 90, tense: "future-continuous", type: "translate_ru_en", question: "Я встречаюсь с Джоном в 5. Мы договорились вчера. (договорённость)", correctAnswer: "I am meeting John at 5. We arranged it yesterday", explanation: "Договорённость → Present Continuous: am meeting. НЕ will be meeting.", hintIds: ["ftc-vs-present-continuous", "ftc-usage-expected"] },
  { id: 91, tense: "future-continuous", type: "translate_ru_en", question: "В 5 вечера я буду встречаться с Джоном. (в процессе, без договорённости)", correctAnswer: "I will be meeting John at 5 pm", explanation: "Ожидаемый процесс без жёсткой договорённости → will be meeting.", hintIds: ["ftc-vs-present-continuous", "ftc-usage-process"] },

  // FC vs going to comparisons
  { id: 92, tense: "future-continuous", type: "translate_ru_en", question: "Я собираюсь изучать медицину в университете. (намерение)", correctAnswer: "I am going to study medicine at university", explanation: "Намерение → be going to. НЕ Future Continuous для намерений.", hintIds: ["ftc-vs-going-to", "ftc-usage-expected"] },
  { id: 93, tense: "future-continuous", type: "translate_ru_en", question: "Через год она будет изучать медицину в университете. (будет в процессе)", correctAnswer: "In a year she will be studying medicine at university", explanation: "Действие будет в процессе через год → will be studying.", hintIds: ["ftc-vs-going-to", "ftc-usage-process"] },

  // Stative verbs — must use Future Simple, NOT Future Continuous
  { id: 94, tense: "future-continuous", type: "translate_ru_en", question: "К завтрашнему дню я буду знать результат. (NOT: will be knowing)", correctAnswer: "I will know the result by tomorrow", explanation: "Know — стативный глагол, НЕ используется в Continuous. Future Simple: will know.", hintIds: ["ftc-stative", "ftc-stative-list"] },
  { id: 95, tense: "future-continuous", type: "translate_ru_en", question: "Она будет владеть этой машиной ещё много лет. (NOT: will be owning)", correctAnswer: "She will own this car for many more years", explanation: "Own — стативный глагол (владение) → Future Simple: will own.", hintIds: ["ftc-stative", "ftc-dual-have"] },
  { id: 96, tense: "future-continuous", type: "translate_ru_en", question: "Завтра я буду видеть своего dentist. (встреча, NOT: see = видеть)", correctAnswer: "I will be seeing my dentist tomorrow", explanation: "See как 'встречаться с' = действие → CAN use Future Continuous: will be seeing.", hintIds: ["ftc-dual-see", "ftc-usage-process"] },
  { id: 97, tense: "future-continuous", type: "translate_ru_en", question: "Я буду думать об этом всю ночь. (размышление)", correctAnswer: "I will be thinking about it all night", explanation: "Think как размышление = процесс → CAN use Future Continuous: will be thinking.", hintIds: ["ftc-dual-think", "ftc-usage-process"] },

  // Time clauses — do NOT use will in when/while/if clauses
  { id: 98, tense: "future-continuous", type: "translate_ru_en", question: "Когда я закончу работу, я буду отдыхать.", correctAnswer: "When I finish work, I will be relaxing", explanation: "When + Present Simple (finish), главное: will be relaxing. НЕ when I will finish.", hintIds: ["ftc-time-clauses", "ftc-usage-background"] },
  { id: 99, tense: "future-continuous", type: "translate_ru_en", question: "Пока он будет готовить, я буду накрывать на стол.", correctAnswer: "While he is cooking, I will be setting the table", explanation: "While + Present Continuous (is cooking), главное: will be setting.", hintIds: ["ftc-time-clauses", "ftc-signal-while"] },

  // Spelling — edge cases
  { id: 100, tense: "future-continuous", type: "translate_ru_en", question: "Завтра в это время они будут гулять по парку.", correctAnswer: "They will be strolling through the park this time tomorrow", explanation: "Future Continuous: will be strolling. Stroll → strolling (удваиваем l после краткого гласного).", hintIds: ["ftc-spelling-double", "ftc-signal-at-time"] },
];
