import type { Exercise } from "@/lib/tutor-data";

// ============================================================
// Future Simple — 100 exercises
// ============================================================

export const futureSimpleExercises: Exercise[] = [
  // ===== Multiple Choice (1–35) =====
  // Basic will + V1 (affirmative) — one-time actions
  { id: 1, tense: "future-simple", type: "multiple_choice", question: "She ___ tomorrow morning.", options: ["will come", "comes", "is coming", "is going to come"], correctAnswer: "will come", explanation: "Future Simple: will + V1. Одноразовое действие в будущем, no prior plan.", hintIds: ["fts-formula", "fts-signal-tomorrow"] },
  { id: 2, tense: "future-simple", type: "multiple_choice", question: "I ___ you later this evening.", options: ["will call", "am calling", "call", "am going to call"], correctAnswer: "will call", explanation: "Future Simple: will + V1. Обещание / одноразовое действие в будущем.", hintIds: ["fts-formula", "fts-usage-promise"] },
  { id: 3, tense: "future-simple", type: "multiple_choice", question: "They ___ the exam next week.", options: ["will pass", "pass", "are passing", "are going to pass"], correctAnswer: "will pass", explanation: "Future Simple: will + V1. Предсказание без очевидных доказательств.", hintIds: ["fts-formula", "fts-usage-prediction"] },
  { id: 4, tense: "future-simple", type: "multiple_choice", question: "He ___ the document by email.", options: ["will send", "sends", "is sending", "is going to send"], correctAnswer: "will send", explanation: "Future Simple: will + V1. Одноразовое действие в будущем.", hintIds: ["fts-formula", "fts-usage-onetime"] },
  { id: 5, tense: "future-simple", type: "multiple_choice", question: "We ___ at the hotel for two nights.", options: ["will stay", "stay", "are staying", "are going to stay"], correctAnswer: "will stay", explanation: "Future Simple: will + V1. Решение о будущем действии.", hintIds: ["fts-formula", "fts-usage-onetime"] },
  // Predictions
  { id: 6, tense: "future-simple", type: "multiple_choice", question: "I think she ___ the competition.", options: ["will win", "wins", "is winning", "is going to win"], correctAnswer: "will win", explanation: "Предсказание на основе мнения (I think) → Future Simple: will win.", hintIds: ["fts-usage-prediction", "fts-signal-prediction"] },
  { id: 7, tense: "future-simple", type: "multiple_choice", question: "People ___ on Mars in the next fifty years.", options: ["will live", "live", "are living", "are going to live"], correctAnswer: "will live", explanation: "Предсказание о далёком будущем → Future Simple: will live.", hintIds: ["fts-usage-prediction", "fts-signal-in"] },
  { id: 8, tense: "future-simple", type: "multiple_choice", question: "It ___ cold tomorrow, I'm sure.", options: ["will be", "is", "is being", "is going to be"], correctAnswer: "will be", explanation: "Предсказание (I'm sure) → Future Simple: will be.", hintIds: ["fts-usage-prediction", "fts-signal-tomorrow"] },
  // Promises
  { id: 9, tense: "future-simple", type: "multiple_choice", question: "I ___ you with your homework, I promise.", options: ["will help", "help", "am helping", "am going to help"], correctAnswer: "will help", explanation: "Обещание → Future Simple: will help. Promise = типичный маркер Future Simple.", hintIds: ["fts-usage-promise", "fts-formula"] },
  { id: 10, tense: "future-simple", type: "multiple_choice", question: "She ___ anyone about your secret.", options: ["won't tell", "doesn't tell", "isn't telling", "isn't going to tell"], correctAnswer: "won't tell", explanation: "Обещание не делать что-то → won't + V1.", hintIds: ["fts-usage-promise", "fts-negative"] },
  // Negative: won't + V1
  { id: 11, tense: "future-simple", type: "multiple_choice", question: "He ___ to the party tonight.", options: ["won't come", "doesn't come", "isn't coming", "isn't going to come"], correctAnswer: "won't come", explanation: "Future Simple отрицание: won't + V1. Он не придёт на вечеринку.", hintIds: ["fts-negative", "fts-usage-onetime"] },
  { id: 12, tense: "future-simple", type: "multiple_choice", question: "The car ___ — the engine is completely broken.", options: ["won't start", "doesn't start", "isn't starting", "isn't going to start"], correctAnswer: "won't start", explanation: "Won't может выражать отказ / упорное нежелание: машина не заводится.", hintIds: ["fts-negative", "fts-wont-refusal"] },
  { id: 13, tense: "future-simple", type: "multiple_choice", question: "She ___ him again after what happened.", options: ["won't see", "doesn't see", "isn't seeing", "isn't going to see"], correctAnswer: "won't see", explanation: "Future Simple отрицание: won't see. Решение не делать что-то.", hintIds: ["fts-negative", "fts-usage-onetime"] },
  { id: 14, tense: "future-simple", type: "multiple_choice", question: "They ___ the deadline, I'm afraid.", options: ["won't meet", "don't meet", "aren't meeting", "aren't going to meet"], correctAnswer: "won't meet", explanation: "Future Simple отрицание: won't meet. Предсказание-отрицание.", hintIds: ["fts-negative", "fts-usage-prediction"] },
  { id: 15, tense: "future-simple", type: "multiple_choice", question: "The door ___ — I think it's locked.", options: ["won't open", "doesn't open", "isn't opening", "isn't going to open"], correctAnswer: "won't open", explanation: "Won't + V1 выражает отказ: дверь не открывается (упорно).", hintIds: ["fts-negative", "fts-wont-refusal"] },
  // Questions: Will...?
  { id: 16, tense: "future-simple", type: "multiple_choice", question: "___ you ___ at the meeting tomorrow?", options: ["Will / be", "Do / be", "Are / being", "Are / going to be"], correctAnswer: "Will / be", explanation: "Вопрос в Future Simple: Will + подлежащее + V1?", hintIds: ["fts-question", "fts-signal-tomorrow"] },
  { id: 17, tense: "future-simple", type: "multiple_choice", question: "___ she ___ the job?", options: ["Will / accept", "Does / accept", "Is / accepting", "Is / going to accept"], correctAnswer: "Will / accept", explanation: "Вопрос в Future Simple: Will + she + V1?", hintIds: ["fts-question", "fts-usage-onetime"] },
  { id: 18, tense: "future-simple", type: "multiple_choice", question: "___ they ___ us with the project?", options: ["Will / help", "Do / help", "Are / helping", "Are / going to help"], correctAnswer: "Will / help", explanation: "Вопрос-просьба о помощи: Will they help?", hintIds: ["fts-question", "fts-usage-onetime"] },
  { id: 19, tense: "future-simple", type: "multiple_choice", question: "___ it ___ long?", options: ["Will / take", "Does / take", "Is / taking", "Is / going to take"], correctAnswer: "Will / take", explanation: "Вопрос в Future Simple: Will + it + V1?", hintIds: ["fts-question", "fts-usage-onetime"] },
  { id: 20, tense: "future-simple", type: "multiple_choice", question: "— Will you be there? — ___.", options: ["Yes, I will", "Yes, I do", "Yes, I am", "Yes, I going to"], correctAnswer: "Yes, I will", explanation: "Краткий ответ на Will-вопрос: Yes, I will. / No, I won't.", hintIds: ["fts-question", "fts-formula"] },
  // Wh-questions
  { id: 21, tense: "future-simple", type: "multiple_choice", question: "What ___ you ___ tomorrow?", options: ["will / do", "do / do", "are / doing", "are / going to do"], correctAnswer: "will / do", explanation: "Wh-вопрос в Future Simple: What + will + you + V1?", hintIds: ["fts-wh-question", "fts-signal-tomorrow"] },
  { id: 22, tense: "future-simple", type: "multiple_choice", question: "Where ___ she ___ for her holiday?", options: ["will / go", "does / go", "is / going", "is / going to go"], correctAnswer: "will / go", explanation: "Wh-вопрос: Where + will + she + V1?", hintIds: ["fts-wh-question", "fts-usage-onetime"] },
  { id: 23, tense: "future-simple", type: "multiple_choice", question: "How long ___ the journey ___?", options: ["will / take", "does / take", "is / taking", "is / going to take"], correctAnswer: "will / take", explanation: "Wh-вопрос: How long + will + it + V1?", hintIds: ["fts-wh-question", "fts-usage-onetime"] },
  { id: 24, tense: "future-simple", type: "multiple_choice", question: "When ___ he ___ back?", options: ["will / come", "does / come", "is / coming", "is / going to come"], correctAnswer: "will / come", explanation: "Wh-вопрос: When + will + he + V1?", hintIds: ["fts-wh-question", "fts-usage-onetime"] },
  { id: 25, tense: "future-simple", type: "multiple_choice", question: "Who ___ the bill?", options: ["will pay", "pays", "is paying", "is going to pay"], correctAnswer: "will pay", explanation: "Wh-вопрос с who: Who + will + V1?", hintIds: ["fts-wh-question", "fts-usage-onetime"] },
  // Spontaneous decisions
  { id: 26, tense: "future-simple", type: "multiple_choice", question: "— The phone is ringing! — I ___ it!", options: ["will answer", "answer", "am answering", "am going to answer"], correctAnswer: "will answer", explanation: "Спонтанное решение в момент речи → Future Simple: I'll answer it!", hintIds: ["fts-usage-spontaneous", "fts-formula"] },
  { id: 27, tense: "future-simple", type: "multiple_choice", question: "— I'm hungry. — I ___ a sandwich for you.", options: ["will make", "make", "am making", "am going to make"], correctAnswer: "will make", explanation: "Спонтанное предложение → Future Simple: I'll make a sandwich.", hintIds: ["fts-usage-spontaneous", "fts-usage-offer"] },
  { id: 28, tense: "future-simple", type: "multiple_choice", question: "— It's cold in here. — I ___ the window.", options: ["will close", "close", "am closing", "am going to close"], correctAnswer: "will close", explanation: "Спонтанное решение закрыть окно → Future Simple: I'll close the window.", hintIds: ["fts-usage-spontaneous", "fts-formula"] },
  // Offers and requests: Shall I...? / Will you...?
  { id: 29, tense: "future-simple", type: "multiple_choice", question: "___ I open the window?", options: ["Shall", "Will", "Do", "Am"], correctAnswer: "Shall", explanation: "Shall I...? — предложение помощи (британский английский).", hintIds: ["fts-shall", "fts-usage-offer"] },
  { id: 30, tense: "future-simple", type: "multiple_choice", question: "___ you help me carry these bags?", options: ["Will", "Do", "Are", "Shall"], correctAnswer: "Will", explanation: "Will you...? — вежливая просьба.", hintIds: ["fts-usage-offer", "fts-question"] },
  { id: 31, tense: "future-simple", type: "multiple_choice", question: "___ we go for a walk after dinner?", options: ["Shall", "Will", "Do", "Are"], correctAnswer: "Shall", explanation: "Shall we...? — предложение совместного действия (британский английский).", hintIds: ["fts-shall", "fts-usage-offer"] },
  // Future Simple vs be going to
  { id: 32, tense: "future-simple", type: "multiple_choice", question: "Look at those dark clouds! It ___ rain.", options: ["is going to", "will", "rains", "is raining"], correctAnswer: "is going to", explanation: "Очевидные доказательства (тёмные тучи) → be going to, NOT will.", hintIds: ["fts-vs-going-to", "fts-usage-prediction"] },
  { id: 33, tense: "future-simple", type: "multiple_choice", question: "I think people ___ more electric cars in the future.", options: ["will drive", "are going to drive", "drive", "are driving"], correctAnswer: "will drive", explanation: "Предсказание на основе мнения (I think) → will, NOT be going to.", hintIds: ["fts-vs-going-to", "fts-usage-prediction"] },
  { id: 34, tense: "future-simple", type: "multiple_choice", question: "She has already packed her bags. She ___ to Paris tomorrow.", options: ["is going", "will go", "goes", "is going to go"], correctAnswer: "is going", explanation: "Запланированное действие с договорённостью → Present Continuous (is going), NOT will.", hintIds: ["fts-vs-present-continuous", "fts-usage-onetime"] },
  { id: 35, tense: "future-simple", type: "multiple_choice", question: "— We've run out of milk. — I ___ to the shop and get some.", options: ["will go", "am going", "go", "am going to go"], correctAnswer: "will go", explanation: "Спонтанное решение → Future Simple: I'll go.", hintIds: ["fts-usage-spontaneous", "fts-vs-going-to"] },

  // ===== Fill in the Blank (36–65) =====
  // Basic will + V1 (affirmative)
  { id: 36, tense: "future-simple", type: "fill_blank", question: "She ___ (come) to the office next Monday.", correctAnswer: "will come", explanation: "Future Simple: will + V1. Придёт в офис в следующий понедельник.", hintIds: ["fts-formula", "fts-usage-onetime"] },
  { id: 37, tense: "future-simple", type: "fill_blank", question: "I ___ (send) you the report by Friday.", correctAnswer: "will send", explanation: "Future Simple: will + V1. Обещание отправить отчёт к пятнице.", hintIds: ["fts-formula", "fts-usage-promise"] },
  { id: 38, tense: "future-simple", type: "fill_blank", question: "They ___ (arrive) in London tomorrow evening.", correctAnswer: "will arrive", explanation: "Future Simple: will + V1. Прибудут в Лондон завтра вечером.", hintIds: ["fts-formula", "fts-signal-tomorrow"] },
  { id: 39, tense: "future-simple", type: "fill_blank", question: "He ___ (finish) the work by the deadline.", correctAnswer: "will finish", explanation: "Future Simple: will + V1. Закончит работу к сроку.", hintIds: ["fts-formula", "fts-usage-promise"] },
  { id: 40, tense: "future-simple", type: "fill_blank", question: "We ___ (meet) them at the airport.", correctAnswer: "will meet", explanation: "Future Simple: will + V1. Встретим их в аэропорту.", hintIds: ["fts-formula", "fts-usage-onetime"] },
  // Predictions
  { id: 41, tense: "future-simple", type: "fill_blank", question: "I'm sure he ___ (pass) the driving test.", correctAnswer: "will pass", explanation: "Предсказание на основе уверенности (I'm sure) → will pass.", hintIds: ["fts-usage-prediction", "fts-signal-prediction"] },
  { id: 42, tense: "future-simple", type: "fill_blank", question: "I don't think they ___ (win) the match.", correctAnswer: "will win", explanation: "Предсказание с I don't think → won't win или will win в отрицательном предложении.", hintIds: ["fts-usage-prediction", "fts-signal-prediction"] },
  { id: 43, tense: "future-simple", type: "fill_blank", question: "In the future, robots ___ (do) most household chores.", correctAnswer: "will do", explanation: "Предсказание о будущем → will do.", hintIds: ["fts-usage-prediction", "fts-signal-in"] },
  // Negative: won't + V1
  { id: 44, tense: "future-simple", type: "fill_blank", question: "She ___ (not / come) to the party. She's busy.", correctAnswer: "won't come", explanation: "Future Simple отрицание: won't + V1. Она не придёт — занята.", hintIds: ["fts-negative", "fts-usage-onetime"] },
  { id: 45, tense: "future-simple", type: "fill_blank", question: "He ___ (not / forget) your birthday, I promise.", correctAnswer: "won't forget", explanation: "Обещание-отрицание: won't forget. Не забудет твой день рождения.", hintIds: ["fts-negative", "fts-usage-promise"] },
  { id: 46, tense: "future-simple", type: "fill_blank", question: "The old printer ___ (not / work) with this computer.", correctAnswer: "won't work", explanation: "Won't work — отказ / нежелание работать: принтер не будет работать.", hintIds: ["fts-negative", "fts-wont-refusal"] },
  { id: 47, tense: "future-simple", type: "fill_blank", question: "I ___ (not / be) late again, I promise.", correctAnswer: "won't be", explanation: "Обещание-отрицание: won't be. Не опоздаю снова.", hintIds: ["fts-negative", "fts-usage-promise"] },
  // Questions: Will...?
  { id: 48, tense: "future-simple", type: "fill_blank", question: "___ (you / be) at home tomorrow evening?", correctAnswer: "Will you be", explanation: "Вопрос в Future Simple: Will + you + V1?", hintIds: ["fts-question", "fts-signal-tomorrow"] },
  { id: 49, tense: "future-simple", type: "fill_blank", question: "___ (she / like) the gift?", correctAnswer: "Will she like", explanation: "Вопрос-предсказание: Will she like the gift?", hintIds: ["fts-question", "fts-usage-prediction"] },
  { id: 50, tense: "future-simple", type: "fill_blank", question: "___ (it / rain) this weekend?", correctAnswer: "Will it rain", explanation: "Вопрос-предсказание: Will it rain?", hintIds: ["fts-question", "fts-usage-prediction"] },
  // Wh-questions
  { id: 51, tense: "future-simple", type: "fill_blank", question: "When ___ (they / arrive)?", correctAnswer: "will they arrive", explanation: "Wh-вопрос: When + will + they + V1?", hintIds: ["fts-wh-question", "fts-usage-onetime"] },
  { id: 52, tense: "future-simple", type: "fill_blank", question: "How much ___ (it / cost)?", correctAnswer: "will it cost", explanation: "Wh-вопрос: How much + will + it + V1?", hintIds: ["fts-wh-question", "fts-usage-onetime"] },
  { id: 53, tense: "future-simple", type: "fill_blank", question: "Who ___ (win) the election?", correctAnswer: "will win", explanation: "Wh-вопрос с who (подлежащее): Who + will + V1?", hintIds: ["fts-wh-question", "fts-usage-prediction"] },
  // Spontaneous decisions
  { id: 54, tense: "future-simple", type: "fill_blank", question: "— I've lost my keys! — I ___ (help) you look for them.", correctAnswer: "will help", explanation: "Спонтанное предложение помощи → I'll help you.", hintIds: ["fts-usage-spontaneous", "fts-usage-offer"] },
  { id: 55, tense: "future-simple", type: "fill_blank", question: "— Someone is at the door. — I ___ (open) it.", correctAnswer: "will open", explanation: "Спонтанное решение → I'll open it.", hintIds: ["fts-usage-spontaneous", "fts-formula"] },
  { id: 56, tense: "future-simple", type: "fill_blank", question: "— We don't have any bread. — I ___ (buy) some on my way home.", correctAnswer: "will buy", explanation: "Спонтанное решение купить хлеб → I'll buy some.", hintIds: ["fts-usage-spontaneous", "fts-formula"] },
  // Offers: Shall I...? / Shall we...?
  { id: 57, tense: "future-simple", type: "fill_blank", question: "___ (I / carry) that bag for you?", correctAnswer: "Shall I carry", explanation: "Shall I + V1 — предложение помощи (британский английский).", hintIds: ["fts-shall", "fts-usage-offer"] },
  { id: 58, tense: "future-simple", type: "fill_blank", question: "___ (we / order) pizza for dinner?", correctAnswer: "Shall we order", explanation: "Shall we + V1 — предложение совместного действия.", hintIds: ["fts-shall", "fts-usage-offer"] },
  // Future Simple vs be going to
  { id: 59, tense: "future-simple", type: "fill_blank", question: "Watch out! You ___ (fall) off the ladder! (evidence — you are losing balance)", correctAnswer: "are going to fall", explanation: "Очевидные доказательства прямо сейчас (теряешь равновесие) → be going to, NOT will.", hintIds: ["fts-vs-going-to", "fts-usage-prediction"] },
  { id: 60, tense: "future-simple", type: "fill_blank", question: "I believe she ___ (become) a great doctor one day. (opinion)", correctAnswer: "will become", explanation: "Предсказание на основе мнения (I believe) → will become.", hintIds: ["fts-vs-going-to", "fts-usage-prediction"] },
  // Future Simple vs Present Simple (timetable)
  { id: 61, tense: "future-simple", type: "fill_blank", question: "The train ___ (leave) at 8:00 tomorrow. (timetable)", correctAnswer: "leaves", explanation: "Расписание → Present Simple: leaves. NOT will leave для timetable.", hintIds: ["fts-vs-present-simple", "fts-signal-time-clauses"] },
  { id: 62, tense: "future-simple", type: "fill_blank", question: "I ___ (take) the 8 o'clock train tomorrow. (personal decision)", correctAnswer: "will take", explanation: "Личное решение, а не расписание → Future Simple: will take.", hintIds: ["fts-vs-present-simple", "fts-usage-onetime"] },
  // Future Simple vs Present Continuous (arrangements)
  { id: 63, tense: "future-simple", type: "fill_blank", question: "I ___ (meet) John at 5 pm. We arranged it yesterday.", correctAnswer: "am meeting", explanation: "Договорённость (arranged) → Present Continuous: am meeting, NOT will meet.", hintIds: ["fts-vs-present-continuous", "fts-usage-onetime"] },
  { id: 64, tense: "future-simple", type: "fill_blank", question: "I ___ (meet) John sometime next week. (no arrangement yet)", correctAnswer: "will meet", explanation: "Нет договорённости → Future Simple: will meet.", hintIds: ["fts-vs-present-continuous", "fts-usage-onetime"] },
  // Time clauses: when/if + Present Simple
  { id: 65, tense: "future-simple", type: "fill_blank", question: "I ___ (call) you when I ___ (arrive) at the hotel.", correctAnswer: "will call / arrive", explanation: "Главное предложение — Future Simple (will call), придаточное времени — Present Simple (arrive). НЕ when I will arrive!", hintIds: ["fts-time-clauses", "fts-no-double-future"] },

  // ===== Translate RU → EN (66–100) =====
  // Basic will + V1 (affirmative)
  { id: 66, tense: "future-simple", type: "translate_ru_en", question: "Я позвоню тебе завтра.", correctAnswer: "I will call you tomorrow", explanation: "Future Simple: will + V1. Одноразовое действие в будущем.", hintIds: ["fts-formula", "fts-signal-tomorrow"] },
  { id: 67, tense: "future-simple", type: "translate_ru_en", question: "Она пришлёт тебе письмо на следующей неделе.", correctAnswer: "She will send you a letter next week", explanation: "Future Simple: will + V1. Одноразовое действие в будущем.", hintIds: ["fts-formula", "fts-usage-onetime"] },
  { id: 68, tense: "future-simple", type: "translate_ru_en", question: "Мы поедем в Париж в следующем месяце.", correctAnswer: "We will go to Paris next month", explanation: "Future Simple: will + V1. Одноразовое действие в будущем.", hintIds: ["fts-formula", "fts-usage-onetime"] },
  // Predictions
  { id: 69, tense: "future-simple", type: "translate_ru_en", question: "Я думаю, он сдаст экзамен.", correctAnswer: "I think he will pass the exam", explanation: "Предсказание на основе мнения (I think) → will pass.", hintIds: ["fts-usage-prediction", "fts-signal-prediction"] },
  { id: 70, tense: "future-simple", type: "translate_ru_en", question: "В будущем люди будут жить дольше.", correctAnswer: "In the future people will live longer", explanation: "Предсказание о будущем → will live.", hintIds: ["fts-usage-prediction", "fts-signal-in"] },
  // Promises
  { id: 71, tense: "future-simple", type: "translate_ru_en", question: "Я обещаю, что не опоздаю.", correctAnswer: "I promise I won't be late", explanation: "Обещание-отрицание: won't be late.", hintIds: ["fts-usage-promise", "fts-negative"] },
  { id: 72, tense: "future-simple", type: "translate_ru_en", question: "Я всегда буду любить тебя.", correctAnswer: "I will always love you", explanation: "Обещание: will always love. Наречие always ставится между will и V1.", hintIds: ["fts-usage-promise", "fts-formula"] },
  // Negative: won't
  { id: 73, tense: "future-simple", type: "translate_ru_en", question: "Он не придёт на собрание.", correctAnswer: "He won't come to the meeting", explanation: "Future Simple отрицание: won't come.", hintIds: ["fts-negative", "fts-usage-onetime"] },
  { id: 74, tense: "future-simple", type: "translate_ru_en", question: "Машина не заводится. (отказ машины)", correctAnswer: "The car won't start", explanation: "Won't выражает отказ / упорное нежелание: машина не заводится.", hintIds: ["fts-negative", "fts-wont-refusal"] },
  { id: 75, tense: "future-simple", type: "translate_ru_en", question: "Она не расскажет никому твой секрет.", correctAnswer: "She won't tell anyone your secret", explanation: "Future Simple отрицание: won't tell. Обещание молчать.", hintIds: ["fts-negative", "fts-usage-promise"] },
  // Questions
  { id: 76, tense: "future-simple", type: "translate_ru_en", question: "Ты будешь дома завтра вечером?", correctAnswer: "Will you be at home tomorrow evening", explanation: "Вопрос в Future Simple: Will + you + V1?", hintIds: ["fts-question", "fts-signal-tomorrow"] },
  { id: 77, tense: "future-simple", type: "translate_ru_en", question: "Она согласится на эту работу?", correctAnswer: "Will she accept the job", explanation: "Вопрос-предсказание: Will she accept the job?", hintIds: ["fts-question", "fts-usage-prediction"] },
  // Wh-questions
  { id: 78, tense: "future-simple", type: "translate_ru_en", question: "Когда ты вернёшься из отпуска?", correctAnswer: "When will you return from your holiday", explanation: "Wh-вопрос: When + will + you + V1?", hintIds: ["fts-wh-question", "fts-usage-onetime"] },
  { id: 79, tense: "future-simple", type: "translate_ru_en", question: "Сколько времени займёт дорога?", correctAnswer: "How long will the journey take", explanation: "Wh-вопрос: How long + will + it + V1?", hintIds: ["fts-wh-question", "fts-usage-onetime"] },
  // Spontaneous decisions
  { id: 80, tense: "future-simple", type: "translate_ru_en", question: "— Звонит телефон! — Я отвечу!", correctAnswer: "The phone is ringing! I will answer it", explanation: "Спонтанное решение → I'll answer it!", hintIds: ["fts-usage-spontaneous", "fts-formula"] },
  { id: 81, tense: "future-simple", type: "translate_ru_en", question: "— Я голоден. — Я сделаю тебе бутерброд.", correctAnswer: "I'm hungry. I will make you a sandwich", explanation: "Спонтанное предложение → I'll make you a sandwich.", hintIds: ["fts-usage-spontaneous", "fts-usage-offer"] },
  { id: 82, tense: "future-simple", type: "translate_ru_en", question: "— У нас закончилось молоко. — Я схожу в магазин.", correctAnswer: "We've run out of milk. I will go to the shop", explanation: "Спонтанное решение → I'll go to the shop.", hintIds: ["fts-usage-spontaneous", "fts-formula"] },
  // Offers: Shall I / Shall we
  { id: 83, tense: "future-simple", type: "translate_ru_en", question: "Мне открыть окно?", correctAnswer: "Shall I open the window", explanation: "Shall I + V1 — предложение помощи (британский английский).", hintIds: ["fts-shall", "fts-usage-offer"] },
  { id: 84, tense: "future-simple", type: "translate_ru_en", question: "Пойдём гулять после ужина?", correctAnswer: "Shall we go for a walk after dinner", explanation: "Shall we + V1 — предложение совместного действия.", hintIds: ["fts-shall", "fts-usage-offer"] },
  { id: 85, tense: "future-simple", type: "translate_ru_en", question: "Помочь тебе с сумками?", correctAnswer: "Shall I help you with the bags", explanation: "Shall I + V1 — предложение помощи.", hintIds: ["fts-shall", "fts-usage-offer"] },
  // Future Simple vs be going to
  { id: 86, tense: "future-simple", type: "translate_ru_en", question: "Посмотри на эти тучи! Собирается дождь. (есть доказательства)", correctAnswer: "Look at those clouds! It is going to rain", explanation: "Очевидные доказательства (тучи) → be going to, NOT will.", hintIds: ["fts-vs-going-to", "fts-usage-prediction"] },
  { id: 87, tense: "future-simple", type: "translate_ru_en", question: "Я думаю, что в будущем люди будут летать на Марс.", correctAnswer: "I think people will fly to Mars in the future", explanation: "Предсказание на основе мнения → will, NOT be going to.", hintIds: ["fts-vs-going-to", "fts-usage-prediction"] },
  { id: 88, tense: "future-simple", type: "translate_ru_en", question: "Она уже купила билеты. Она собирается поехать в Рим на выходные. (запланировано)", correctAnswer: "She has already bought the tickets. She is going to go to Rome for the weekend", explanation: "Запланированное действие (купила билеты) → be going to.", hintIds: ["fts-vs-going-to", "fts-usage-onetime"] },
  // Future Simple vs Present Simple (timetable)
  { id: 89, tense: "future-simple", type: "translate_ru_en", question: "Поезд отправляется в 8 утра. (расписание)", correctAnswer: "The train leaves at 8 am", explanation: "Расписание → Present Simple: leaves. НЕ will leave для timetable.", hintIds: ["fts-vs-present-simple", "fts-signal-time-clauses"] },
  { id: 90, tense: "future-simple", type: "translate_ru_en", question: "Я поеду на восьмичасовом поезде. (личное решение)", correctAnswer: "I will take the 8 o'clock train", explanation: "Личное решение → Future Simple: will take.", hintIds: ["fts-vs-present-simple", "fts-usage-onetime"] },
  // Future Simple vs Present Continuous (arrangements)
  { id: 91, tense: "future-simple", type: "translate_ru_en", question: "Я встречаюсь с Джоном в 5. Мы договорились вчера. (договорённость)", correctAnswer: "I am meeting John at 5. We arranged it yesterday", explanation: "Договорённость → Present Continuous: am meeting, NOT will meet.", hintIds: ["fts-vs-present-continuous", "fts-usage-onetime"] },
  { id: 92, tense: "future-simple", type: "translate_ru_en", question: "Я встречусь с Джоном когда-нибудь на следующей неделе. (без договорённости)", correctAnswer: "I will meet John sometime next week", explanation: "Нет договорённости → Future Simple: will meet.", hintIds: ["fts-vs-present-continuous", "fts-usage-onetime"] },
  // Time clauses: when/if + Present Simple
  { id: 93, tense: "future-simple", type: "translate_ru_en", question: "Я позвоню тебе, когда прибуду в отель.", correctAnswer: "I will call you when I arrive at the hotel", explanation: "Главное предложение — will call, придаточное — when I arrive (Present Simple). НЕ when I will arrive!", hintIds: ["fts-time-clauses", "fts-no-double-future"] },
  { id: 94, tense: "future-simple", type: "translate_ru_en", question: "Если пойдёт дождь, мы останемся дома.", correctAnswer: "If it rains, we will stay at home", explanation: "Первое условное: If + Present Simple (rains), will + V1 (will stay). НЕ If it will rain!", hintIds: ["fts-first-conditional", "fts-no-double-future"] },
  { id: 95, tense: "future-simple", type: "translate_ru_en", question: "Она сообщит нам, как только получит новости.", correctAnswer: "She will let us know as soon as she gets the news", explanation: "As soon as + Present Simple (gets), will + V1 (will let). НЕ as soon as she will get!", hintIds: ["fts-time-clauses", "fts-no-double-future"] },
  // Stative verbs
  { id: 96, tense: "future-simple", type: "translate_ru_en", question: "Я узнаю ответ завтра. (NOT: will be knowing)", correctAnswer: "I will know the answer tomorrow", explanation: "Know — stative verb, не используется в Continuous. Future Simple: will know.", hintIds: ["fts-stative", "fts-stative-list"] },
  { id: 97, tense: "future-simple", type: "translate_ru_en", question: "Она в конце концов поймёт.", correctAnswer: "She will understand eventually", explanation: "Understand — stative verb, не используется в Continuous. Future Simple: will understand.", hintIds: ["fts-stative", "fts-stative-list"] },
  { id: 98, tense: "future-simple", type: "translate_ru_en", question: "Это будет стоить слишком дорого.", correctAnswer: "It will cost too much", explanation: "Cost — stative verb, не используется в Continuous. Future Simple: will cost.", hintIds: ["fts-stative", "fts-stative-list"] },
  // British English: shall
  { id: 99, tense: "future-simple", type: "translate_ru_en", question: "Мне налить тебе чаю?", correctAnswer: "Shall I pour you some tea", explanation: "Shall I + V1 — предложение помощи, типично для британского английского.", hintIds: ["fts-shall", "fts-usage-offer"] },
  { id: 100, tense: "future-simple", type: "translate_ru_en", question: "Начнём урок? (британский вариант)", correctAnswer: "Shall we start the lesson", explanation: "Shall we + V1 — предложение совместного действия (британский английский).", hintIds: ["fts-shall", "fts-usage-offer"] },
];
