import type { Exercise } from "@/lib/tutor-data";

// ============================================================
// Past Perfect Continuous — 100 exercises
// ============================================================

export const pastPerfectContinuousExercises: Exercise[] = [
  // ===== Multiple Choice (1–35) =====
  // Basic had been + V-ing (regular verbs)
  { id: 1, tense: "past-perfect-continuous", type: "multiple_choice", question: "She ___ for three hours before he finally called.", options: ["had been waiting", "has been waiting", "was waiting", "had waited"], correctAnswer: "had been waiting", explanation: "Past Perfect Continuous: had been + V-ing. Длительное действие до момента в прошлом (before he called).", hintIds: ["ptpc-formula", "ptpc-signal-before"] },
  { id: 2, tense: "past-perfect-continuous", type: "multiple_choice", question: "They ___ all morning before the rain stopped.", options: ["had been working", "have been working", "were working", "had worked"], correctAnswer: "had been working", explanation: "Past Perfect Continuous: had been + V-ing. Работали всё утро до того, как дождь прекратился.", hintIds: ["ptpc-formula", "ptpc-signal-all"] },
  { id: 3, tense: "past-perfect-continuous", type: "multiple_choice", question: "He ___ TV for hours before his mum came home.", options: ["had been watching", "has been watching", "was watching", "had watched"], correctAnswer: "had been watching", explanation: "Past Perfect Continuous: had been + V-ing. Смотрел телевизор до прихода мамы.", hintIds: ["ptpc-formula", "ptpc-signal-before"] },
  { id: 4, tense: "past-perfect-continuous", type: "multiple_choice", question: "We ___ the house for weeks before we sold it.", options: ["had been painting", "have been painting", "were painting", "had painted"], correctAnswer: "had been painting", explanation: "Past Perfect Continuous: had been + V-ing. Красили дом неделями до продажи.", hintIds: ["ptpc-formula", "ptpc-usage-duration"] },
  { id: 5, tense: "past-perfect-continuous", type: "multiple_choice", question: "She ___ the report for two days before she submitted it.", options: ["had been preparing", "has been preparing", "was preparing", "had prepared"], correctAnswer: "had been preparing", explanation: "Past Perfect Continuous: had been + V-ing. Готовила отчёт два дня до отправки.", hintIds: ["ptpc-formula", "ptpc-usage-duration"] },
  { id: 6, tense: "past-perfect-continuous", type: "multiple_choice", question: "I ___ for the exam for months before I took it.", options: ["had been studying", "have been studying", "was studying", "had studied"], correctAnswer: "had been studying", explanation: "Past Perfect Continuous: had been + V-ing. Готовился к экзамену месяцами.", hintIds: ["ptpc-formula", "ptpc-usage-duration"] },
  { id: 7, tense: "past-perfect-continuous", type: "multiple_choice", question: "The children ___ in the garden all afternoon before it got dark.", options: ["had been playing", "have been playing", "were playing", "had played"], correctAnswer: "had been playing", explanation: "Past Perfect Continuous: had been + V-ing. Играли весь день до темноты.", hintIds: ["ptpc-formula", "ptpc-signal-all"] },
  { id: 8, tense: "past-perfect-continuous", type: "multiple_choice", question: "He ___ letters all evening before he finally went to bed.", options: ["had been writing", "has been writing", "was writing", "had written"], correctAnswer: "had been writing", explanation: "Past Perfect Continuous: had been + V-ing. Писал письма весь вечер.", hintIds: ["ptpc-formula", "ptpc-signal-all"] },
  // had been + V-ing (irregular verbs)
  { id: 9, tense: "past-perfect-continuous", type: "multiple_choice", question: "She ___ well before the neighbours started renovating.", options: ["had been sleeping", "has been sleeping", "was sleeping", "had slept"], correctAnswer: "had been sleeping", explanation: "Sleep — правильный глагол, но V-ing: sleeping. Past Perfect Continuous: had been sleeping.", hintIds: ["ptpc-formula", "ptpc-signal-before"] },
  { id: 10, tense: "past-perfect-continuous", type: "multiple_choice", question: "He ___ the novel for weeks before he lost it.", options: ["had been writing", "has been writing", "was writing", "had written"], correctAnswer: "had been writing", explanation: "Write → writing (drop-e). Past Perfect Continuous: had been writing.", hintIds: ["ptpc-formula", "ptpc-spelling-ing"] },
  { id: 11, tense: "past-perfect-continuous", type: "multiple_choice", question: "They ___ for hours before they finally reached the summit.", options: ["had been running", "have been running", "were running", "had run"], correctAnswer: "had been running", explanation: "Run → running (удвоение n). Past Perfect Continuous: had been running.", hintIds: ["ptpc-formula", "ptpc-spelling-double"] },
  { id: 12, tense: "past-perfect-continuous", type: "multiple_choice", question: "She ___ all the way to the station before the train left.", options: ["had been walking", "has been walking", "was walking", "had walked"], correctAnswer: "had been walking", explanation: "Walk → walking. Past Perfect Continuous: had been walking. Шла пешком до отхода поезда.", hintIds: ["ptpc-formula", "ptpc-signal-before"] },
  { id: 13, tense: "past-perfect-continuous", type: "multiple_choice", question: "He ___ in the rain for an hour before someone gave him a lift.", options: ["had been standing", "has been standing", "was standing", "had stood"], correctAnswer: "had been standing", explanation: "Stand → standing. Past Perfect Continuous: had been standing. Стоял под дождём час.", hintIds: ["ptpc-formula", "ptpc-usage-duration"] },
  { id: 14, tense: "past-perfect-continuous", type: "multiple_choice", question: "The dog ___ at the door for ten minutes before its owner opened it.", options: ["had been barking", "has been barking", "was barking", "had barked"], correctAnswer: "had been barking", explanation: "Bark → barking. Past Perfect Continuous: had been barking. Лаял десять минут.", hintIds: ["ptpc-formula", "ptpc-usage-duration"] },
  // Negative: hadn't been + V-ing
  { id: 15, tense: "past-perfect-continuous", type: "multiple_choice", question: "She ___ studying before the exam; she was completely unprepared.", options: ["hadn't been", "hasn't been", "wasn't being", "didn't been"], correctAnswer: "hadn't been", explanation: "Past Perfect Continuous отрицание: hadn't been + V-ing. Она не готовилась, поэтому была не готова.", hintIds: ["ptpc-negative", "ptpc-usage-visible-result"] },
  { id: 16, tense: "past-perfect-continuous", type: "multiple_choice", question: "They ___ living together for long before they got married.", options: ["hadn't been", "haven't been", "weren't being", "didn't be"], correctAnswer: "hadn't been", explanation: "Past Perfect Continuous отрицание: hadn't been + V-ing. Они недолго жили вместе до свадьбы.", hintIds: ["ptpc-negative", "ptpc-usage-duration"] },
  { id: 17, tense: "past-perfect-continuous", type: "multiple_choice", question: "He ___ sleeping well before he changed his mattress.", options: ["hadn't been", "hasn't been", "wasn't being", "didn't been"], correctAnswer: "hadn't been", explanation: "Past Perfect Continuous отрицание: hadn't been sleeping well. Плохо спал до смены матраса.", hintIds: ["ptpc-negative", "ptpc-signal-before"] },
  { id: 18, tense: "past-perfect-continuous", type: "multiple_choice", question: "We ___ practising enough before the tournament.", options: ["hadn't been", "haven't been", "weren't being", "didn't be"], correctAnswer: "hadn't been", explanation: "Past Perfect Continuous отрицание: hadn't been practising. Мы недостаточно тренировались.", hintIds: ["ptpc-negative", "ptpc-usage-visible-result"] },
  // Questions: Had + subject + been + V-ing?
  { id: 19, tense: "past-perfect-continuous", type: "multiple_choice", question: "___ she ___ for a long time before you found her?", options: ["Had / been crying", "Has / been crying", "Was / crying", "Did / cry"], correctAnswer: "Had / been crying", explanation: "Вопрос в PPC: Had + подлежащее + been + V-ing?", hintIds: ["ptpc-question", "ptpc-signal-before"] },
  { id: 20, tense: "past-perfect-continuous", type: "multiple_choice", question: "___ they ___ in that house for long before they moved?", options: ["Had / been living", "Have / been living", "Were / living", "Did / live"], correctAnswer: "Had / been living", explanation: "Вопрос в PPC: Had + they + been + V-ing?", hintIds: ["ptpc-question", "ptpc-usage-duration"] },
  { id: 21, tense: "past-perfect-continuous", type: "multiple_choice", question: "___ you ___ before the accident happened?", options: ["Had / been drinking", "Have / been drinking", "Were / drinking", "Did / drink"], correctAnswer: "Had / been drinking", explanation: "Вопрос в PPC: Had + you + been + V-ing?", hintIds: ["ptpc-question", "ptpc-signal-before"] },
  { id: 22, tense: "past-perfect-continuous", type: "multiple_choice", question: "___ he ___ the car for long before it broke down?", options: ["Had / been driving", "Has / been driving", "Was / driving", "Did / drive"], correctAnswer: "Had / been driving", explanation: "Вопрос в PPC: Had + he + been + V-ing?", hintIds: ["ptpc-question", "ptpc-usage-duration"] },
  // Wh-questions
  { id: 23, tense: "past-perfect-continuous", type: "multiple_choice", question: "How long ___ she ___ before the bus came?", options: ["had / been waiting", "has / been waiting", "was / waiting", "did / wait"], correctAnswer: "had / been waiting", explanation: "Wh-вопрос в PPC: How long + had + she + been + V-ing?", hintIds: ["ptpc-wh-question", "ptpc-signal-how-long"] },
  { id: 24, tense: "past-perfect-continuous", type: "multiple_choice", question: "What ___ they ___ before the teacher arrived?", options: ["had / been doing", "have / been doing", "were / doing", "did / do"], correctAnswer: "had / been doing", explanation: "Wh-вопрос в PPC: What + had + they + been + V-ing?", hintIds: ["ptpc-wh-question", "ptpc-signal-before"] },
  { id: 25, tense: "past-perfect-continuous", type: "multiple_choice", question: "Why ___ he ___ before the match started?", options: ["had / been training", "has / been training", "was / training", "did / train"], correctAnswer: "had / been training", explanation: "Wh-вопрос в PPC: Why + had + he + been + V-ing?", hintIds: ["ptpc-wh-question", "ptpc-signal-before"] },
  // by the time + PPC
  { id: 26, tense: "past-perfect-continuous", type: "multiple_choice", question: "By the time we arrived, they ___ for two hours.", options: ["had been arguing", "have been arguing", "were arguing", "had argued"], correctAnswer: "had been arguing", explanation: "By the time + Past Simple → Past Perfect Continuous: had been arguing. Спорили два часа до нашего прихода.", hintIds: ["ptpc-signal-by-the-time", "ptpc-formula"] },
  { id: 27, tense: "past-perfect-continuous", type: "multiple_choice", question: "By the time she turned up, I ___ for forty minutes.", options: ["had been waiting", "have been waiting", "was waiting", "had waited"], correctAnswer: "had been waiting", explanation: "By the time + PS → PPC: had been waiting. Ждал сорок минут.", hintIds: ["ptpc-signal-by-the-time", "ptpc-usage-duration"] },
  { id: 28, tense: "past-perfect-continuous", type: "multiple_choice", question: "By the time the doctor saw him, he ___ in pain for hours.", options: ["had been suffering", "has been suffering", "was suffering", "had suffered"], correctAnswer: "had been suffering", explanation: "By the time + PS → PPC: had been suffering. Страдал от боли часами.", hintIds: ["ptpc-signal-by-the-time", "ptpc-usage-duration"] },
  // for/since + PPC
  { id: 29, tense: "past-perfect-continuous", type: "multiple_choice", question: "She ___ for the company for ten years before she retired.", options: ["had been working", "has been working", "was working", "had worked"], correctAnswer: "had been working", explanation: "For + период → Past Perfect Continuous: had been working for ten years.", hintIds: ["ptpc-signal-for", "ptpc-usage-duration"] },
  { id: 30, tense: "past-perfect-continuous", type: "multiple_choice", question: "He ___ since morning before the electricity went off.", options: ["had been reading", "has been reading", "was reading", "had read"], correctAnswer: "had been reading", explanation: "Since + точка отсчёта → Past Perfect Continuous: had been reading since morning.", hintIds: ["ptpc-signal-since", "ptpc-usage-duration"] },
  { id: 31, tense: "past-perfect-continuous", type: "multiple_choice", question: "They ___ for ages before they finally heard the good news.", options: ["had been waiting", "have been waiting", "were waiting", "had waited"], correctAnswer: "had been waiting", explanation: "For ages → Past Perfect Continuous: had been waiting. Ждали очень долго.", hintIds: ["ptpc-signal-for", "ptpc-formula"] },
  // PPC vs PP (process vs result)
  { id: 32, tense: "past-perfect-continuous", type: "multiple_choice", question: "She was exhausted because she ___.", options: ["had been running", "had run", "was running", "has been running"], correctAnswer: "had been running", explanation: "Был виден результат (исчерпана) длительного процесса → Past Perfect Continuous: had been running.", hintIds: ["ptpc-vs-past-perfect", "ptpc-usage-visible-result"] },
  { id: 33, tense: "past-perfect-continuous", type: "multiple_choice", question: "He ___ the whole room by the time I arrived. (result — the room was clean)", options: ["had cleaned", "had been cleaning", "was cleaning", "has cleaned"], correctAnswer: "had cleaned", explanation: "Результат завершён (комната чистая) → Past Perfect: had cleaned. PPC подчёркивал бы процесс, а не результат.", hintIds: ["ptpc-vs-past-perfect", "ptpc-usage-visible-result"] },
  // Stative verbs → PP not PPC
  { id: 34, tense: "past-perfect-continuous", type: "multiple_choice", question: "By the time they met, she ___ him for years.", options: ["had known", "had been knowing", "has known", "was knowing"], correctAnswer: "had known", explanation: "Know — stative verb, не используется в Continuous. Past Perfect: had known.", hintIds: ["ptpc-stative", "ptpc-stative-list"] },
  { id: 35, tense: "past-perfect-continuous", type: "multiple_choice", question: "He ___ the truth for a long time before he told anyone.", options: ["had believed", "had been believing", "has believed", "was believing"], correctAnswer: "had believed", explanation: "Believe — stative verb, не используется в Continuous. Past Perfect: had believed.", hintIds: ["ptpc-stative", "ptpc-stative-list"] },

  // ===== Fill in the Blank (36–67) =====
  // Affirmative had been + V-ing
  { id: 36, tense: "past-perfect-continuous", type: "fill_blank", question: "She ___ (wait) for two hours before the bus finally arrived.", correctAnswer: "had been waiting", explanation: "Past Perfect Continuous: had been + V-ing. Ждала два часа до прибытия автобуса.", hintIds: ["ptpc-formula", "ptpc-signal-before"] },
  { id: 37, tense: "past-perfect-continuous", type: "fill_blank", question: "They ___ (work) on the project for months before the deadline.", correctAnswer: "had been working", explanation: "Past Perfect Continuous: had been + V-ing. Работали над проектом месяцами.", hintIds: ["ptpc-formula", "ptpc-usage-duration"] },
  { id: 38, tense: "past-perfect-continuous", type: "fill_blank", question: "He ___ (study) French for three years before he moved to Paris.", correctAnswer: "had been studying", explanation: "Past Perfect Continuous: had been + V-ing. Изучал французский три года.", hintIds: ["ptpc-formula", "ptpc-usage-duration"] },
  { id: 39, tense: "past-perfect-continuous", type: "fill_blank", question: "We ___ (travel) all day before we found a hotel.", correctAnswer: "had been travelling", explanation: "Past Perfect Continuous: had been + V-ing. Путешествовали весь день. Travel → travelling (British English, удвоение l).", hintIds: ["ptpc-formula", "ptpc-spelling-double"] },
  { id: 40, tense: "past-perfect-continuous", type: "fill_blank", question: "The baby ___ (cry) for ten minutes before Mum picked her up.", correctAnswer: "had been crying", explanation: "Past Perfect Continuous: had been + V-ing. Ребёнок плакал десять минут.", hintIds: ["ptpc-formula", "ptpc-usage-duration"] },
  { id: 41, tense: "past-perfect-continuous", type: "fill_blank", question: "I ___ (cook) dinner when the guests arrived.", correctAnswer: "had been cooking", explanation: "Past Perfect Continuous: had been + V-ing. Готовил ужин до прихода гостей.", hintIds: ["ptpc-formula", "ptpc-signal-before"] },
  // Negative hadn't been + V-ing
  { id: 42, tense: "past-perfect-continuous", type: "fill_blank", question: "She ___ (not / sleep) well before she went to the doctor.", correctAnswer: "hadn't been sleeping", explanation: "Past Perfect Continuous отрицание: hadn't been + V-ing. Плохо спала до визита к врачу.", hintIds: ["ptpc-negative", "ptpc-usage-visible-result"] },
  { id: 43, tense: "past-perfect-continuous", type: "fill_blank", question: "They ___ (not / train) hard enough before the competition.", correctAnswer: "hadn't been training", explanation: "Past Perfect Continuous отрицание: hadn't been + V-ing. Недостаточно тренировались.", hintIds: ["ptpc-negative", "ptpc-usage-visible-result"] },
  { id: 44, tense: "past-perfect-continuous", type: "fill_blank", question: "He ___ (not / eat) properly for weeks before he collapsed.", correctAnswer: "hadn't been eating", explanation: "Past Perfect Continuous отрицание: hadn't been + V-ing. Недостаточно ел недели до обморока.", hintIds: ["ptpc-negative", "ptpc-usage-duration"] },
  // Questions
  { id: 45, tense: "past-perfect-continuous", type: "fill_blank", question: "___ (she / wait) long before you arrived?", correctAnswer: "Had she been waiting", explanation: "Вопрос в PPC: Had + she + been + V-ing?", hintIds: ["ptpc-question", "ptpc-signal-before"] },
  { id: 46, tense: "past-perfect-continuous", type: "fill_blank", question: "___ (they / live) in London for long before they moved?", correctAnswer: "Had they been living", explanation: "Вопрос в PPC: Had + they + been + V-ing?", hintIds: ["ptpc-question", "ptpc-usage-duration"] },
  { id: 47, tense: "past-perfect-continuous", type: "fill_blank", question: "___ (it / rain) for long before you went out?", correctAnswer: "Had it been raining", explanation: "Вопрос в PPC: Had + it + been + V-ing?", hintIds: ["ptpc-question", "ptpc-usage-duration"] },
  // Wh-questions
  { id: 48, tense: "past-perfect-continuous", type: "fill_blank", question: "How long ___ (you / study) English before you took the exam?", correctAnswer: "had you been studying", explanation: "Wh-вопрос: How long + had + you + been + V-ing?", hintIds: ["ptpc-wh-question", "ptpc-signal-how-long"] },
  { id: 49, tense: "past-perfect-continuous", type: "fill_blank", question: "What ___ (he / do) before the police stopped him?", correctAnswer: "had he been doing", explanation: "Wh-вопрос: What + had + he + been + V-ing?", hintIds: ["ptpc-wh-question", "ptpc-signal-before"] },
  // Double blanks (by the time + PS/PPC, before + PS/PPC)
  { id: 50, tense: "past-perfect-continuous", type: "fill_blank", question: "By the time I ___ (arrive), she ___ (wait) for an hour.", correctAnswer: "arrived / had been waiting", explanation: "By the time + PS (arrived), PPC (had been waiting). Ждала час до моего прихода.", hintIds: ["ptpc-signal-by-the-time", "ptpc-usage-duration"] },
  { id: 51, tense: "past-perfect-continuous", type: "fill_blank", question: "By the time the rain ___ (stop), they ___ (play) football for two hours.", correctAnswer: "stopped / had been playing", explanation: "By the time + PS (stopped), PPC (had been playing). Играли в футбол два часа.", hintIds: ["ptpc-signal-by-the-time", "ptpc-usage-duration"] },
  { id: 52, tense: "past-perfect-continuous", type: "fill_blank", question: "Before she ___ (find) a new job, she ___ (look) for one for six months.", correctAnswer: "found / had been looking", explanation: "Before + PS (found), PPC (had been looking). Искала работу полгода.", hintIds: ["ptpc-signal-before", "ptpc-usage-duration"] },
  { id: 53, tense: "past-perfect-continuous", type: "fill_blank", question: "By the time we ___ (reach) the top, we ___ (climb) for five hours.", correctAnswer: "reached / had been climbing", explanation: "By the time + PS (reached), PPC (had been climbing). Поднимались пять часов.", hintIds: ["ptpc-signal-by-the-time", "ptpc-usage-duration"] },
  { id: 54, tense: "past-perfect-continuous", type: "fill_blank", question: "Before he ___ (get) promoted, he ___ (work) as an assistant for three years.", correctAnswer: "got / had been working", explanation: "Before + PS (got promoted), PPC (had been working). Работал ассистентом три года.", hintIds: ["ptpc-signal-before", "ptpc-usage-duration"] },
  // for/since duration
  { id: 55, tense: "past-perfect-continuous", type: "fill_blank", question: "She ___ (teach) at that school for twenty years before she retired.", correctAnswer: "had been teaching", explanation: "For + период → Past Perfect Continuous: had been teaching for twenty years.", hintIds: ["ptpc-signal-for", "ptpc-usage-duration"] },
  { id: 56, tense: "past-perfect-continuous", type: "fill_blank", question: "He ___ (live) in Moscow since 2005 before he moved to St Petersburg.", correctAnswer: "had been living", explanation: "Since + точка отсчёта → Past Perfect Continuous: had been living since 2005.", hintIds: ["ptpc-signal-since", "ptpc-usage-duration"] },
  { id: 57, tense: "past-perfect-continuous", type: "fill_blank", question: "They ___ (date) for five years before they got engaged.", correctAnswer: "had been dating", explanation: "For + период → Past Perfect Continuous: had been dating for five years.", hintIds: ["ptpc-signal-for", "ptpc-usage-duration"] },
  // all day/morning
  { id: 58, tense: "past-perfect-continuous", type: "fill_blank", question: "She ___ (clean) the house all day before the guests arrived.", correctAnswer: "had been cleaning", explanation: "All day → Past Perfect Continuous: had been cleaning. Убирала весь день.", hintIds: ["ptpc-signal-all", "ptpc-formula"] },
  { id: 59, tense: "past-perfect-continuous", type: "fill_blank", question: "He ___ (type) reports all morning before his computer crashed.", correctAnswer: "had been typing", explanation: "All morning → Past Perfect Continuous: had been typing. Печатал отчёты всё утро.", hintIds: ["ptpc-signal-all", "ptpc-formula"] },
  // PPC vs PP context
  { id: 60, tense: "past-perfect-continuous", type: "fill_blank", question: "She was out of breath because she ___ (run). (focus on the process)", correctAnswer: "had been running", explanation: "Видимый результат процесса (запыхалась) → Past Perfect Continuous: had been running.", hintIds: ["ptpc-vs-past-perfect", "ptpc-usage-visible-result"] },
  { id: 61, tense: "past-perfect-continuous", type: "fill_blank", question: "He ___ (finish) the report by the deadline. (focus on the result)", correctAnswer: "had finished", explanation: "Результат завершён (отчёт готов) → Past Perfect: had finished. Не PPC, потому что важен результат, а не процесс.", hintIds: ["ptpc-vs-past-perfect", "ptpc-usage-visible-result"] },
  { id: 62, tense: "past-perfect-continuous", type: "fill_blank", question: "Her eyes were red because she ___ (cry).", correctAnswer: "had been crying", explanation: "Видимый результат длительного процесса (красные глаза) → Past Perfect Continuous: had been crying.", hintIds: ["ptpc-vs-past-perfect", "ptpc-usage-visible-result"] },
  // Stative verbs
  { id: 63, tense: "past-perfect-continuous", type: "fill_blank", question: "She ___ (understand) the rules before the game started. (use Past Perfect, not PPC)", correctAnswer: "had understood", explanation: "Understand — stative verb, не используется в Continuous. Past Perfect: had understood.", hintIds: ["ptpc-stative", "ptpc-stative-list"] },
  { id: 64, tense: "past-perfect-continuous", type: "fill_blank", question: "He ___ (own) the car for five years before he sold it. (use Past Perfect, not PPC)", correctAnswer: "had owned", explanation: "Own — stative verb, не используется в Continuous. Past Perfect: had owned.", hintIds: ["ptpc-stative", "ptpc-stative-list"] },
  // Spelling -ing rules
  { id: 65, tense: "past-perfect-continuous", type: "fill_blank", question: "She ___ (swim) for an hour before the pool closed. (double the consonant)", correctAnswer: "had been swimming", explanation: "Swim → swimming (удвоение m: краткая гласная + одна согласная). PPC: had been swimming.", hintIds: ["ptpc-spelling-double", "ptpc-formula"] },
  { id: 66, tense: "past-perfect-continuous", type: "fill_blank", question: "He ___ (make) dinner for two hours before the guests arrived. (drop the -e)", correctAnswer: "had been making", explanation: "Make → making (убираем -e перед -ing). PPC: had been making.", hintIds: ["ptpc-spelling-ing", "ptpc-formula"] },
  { id: 67, tense: "past-perfect-continuous", type: "fill_blank", question: "They ___ (lie) on the beach all morning before it started raining. (ie → y)", correctAnswer: "had been lying", explanation: "Lie → lying (ie → y перед -ing). PPC: had been lying.", hintIds: ["ptpc-spelling-ing", "ptpc-formula"] },

  // ===== Translate RU → EN (68–100) =====
  // Basic PPC affirmative sentences
  { id: 68, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Она ждала два часа, прежде чем он позвонил.", correctAnswer: "She had been waiting for two hours before he called", explanation: "Past Perfect Continuous: had been waiting. Длительное действие до момента в прошлом.", hintIds: ["ptpc-formula", "ptpc-signal-before"] },
  { id: 69, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Они работали весь день, прежде чем закончили проект.", correctAnswer: "They had been working all day before they finished the project", explanation: "Past Perfect Continuous: had been working. Работали весь день до завершения.", hintIds: ["ptpc-formula", "ptpc-signal-all"] },
  { id: 70, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Он учил английский три года, прежде чем поехал в Лондон.", correctAnswer: "He had been learning English for three years before he went to London", explanation: "Past Perfect Continuous: had been learning. Учил английский три года.", hintIds: ["ptpc-formula", "ptpc-signal-for"] },
  { id: 71, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Мы искали ключи полчаса, прежде чем нашли их.", correctAnswer: "We had been looking for the keys for half an hour before we found them", explanation: "Past Perfect Continuous: had been looking for. Искали полчаса.", hintIds: ["ptpc-formula", "ptpc-usage-duration"] },
  { id: 72, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Собака лаяла десять минут, прежде чем хозяин вышел.", correctAnswer: "The dog had been barking for ten minutes before its owner came out", explanation: "Past Perfect Continuous: had been barking. Лаяла десять минут.", hintIds: ["ptpc-formula", "ptpc-usage-duration"] },
  { id: 73, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Дети играли в саду всё утро, прежде чем пошёл дождь.", correctAnswer: "The children had been playing in the garden all morning before it started raining", explanation: "Past Perfect Continuous: had been playing. Играли всё утро.", hintIds: ["ptpc-formula", "ptpc-signal-all"] },
  { id: 74, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Я готовил ужин два часа, прежде чем гости пришли.", correctAnswer: "I had been cooking dinner for two hours before the guests arrived", explanation: "Past Perfect Continuous: had been cooking. Готовил два часа.", hintIds: ["ptpc-formula", "ptpc-signal-for"] },
  { id: 75, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Она писала эссе всю ночь, прежде чем сдала его.", correctAnswer: "She had been writing the essay all night before she submitted it", explanation: "Past Perfect Continuous: had been writing. Писала всю ночь. Write → writing (drop -e).", hintIds: ["ptpc-formula", "ptpc-spelling-ing"] },
  // by the time constructions
  { id: 76, tense: "past-perfect-continuous", type: "translate_ru_en", question: "К тому времени как мы приехали, они спорили уже два часа.", correctAnswer: "By the time we arrived, they had been arguing for two hours", explanation: "By the time + PS (arrived), PPC (had been arguing). Спорили два часа.", hintIds: ["ptpc-signal-by-the-time", "ptpc-usage-duration"] },
  { id: 77, tense: "past-perfect-continuous", type: "translate_ru_en", question: "К тому времени как пришёл врач, пациент страдал от боли три часа.", correctAnswer: "By the time the doctor came, the patient had been suffering from pain for three hours", explanation: "By the time + PS (came), PPC (had been suffering). Страдал три часа.", hintIds: ["ptpc-signal-by-the-time", "ptpc-usage-duration"] },
  { id: 78, tense: "past-perfect-continuous", type: "translate_ru_en", question: "К тому времени как она вернулась, я ждал сорок минут.", correctAnswer: "By the time she returned, I had been waiting for forty minutes", explanation: "By the time + PS (returned), PPC (had been waiting). Ждал сорок минут.", hintIds: ["ptpc-signal-by-the-time", "ptpc-usage-duration"] },
  { id: 79, tense: "past-perfect-continuous", type: "translate_ru_en", question: "К тому времени как начался концерт, публика ждала полтора часа.", correctAnswer: "By the time the concert started, the audience had been waiting for an hour and a half", explanation: "By the time + PS (started), PPC (had been waiting). Публика ждала полтора часа.", hintIds: ["ptpc-signal-by-the-time", "ptpc-usage-duration"] },
  // before/after + PPC
  { id: 80, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Прежде чем найти новую работу, она искала её полгода.", correctAnswer: "Before she found a new job, she had been looking for one for six months", explanation: "Before + PS (found), PPC (had been looking). Искала полгода.", hintIds: ["ptpc-signal-before", "ptpc-usage-duration"] },
  { id: 81, tense: "past-perfect-continuous", type: "translate_ru_en", question: "После того как он бегал два часа, он почувствовал себя плохо.", correctAnswer: "After he had been running for two hours, he felt ill", explanation: "After + PPC (had been running), PS (felt ill). Бегал два часа, потом стало плохо.", hintIds: ["ptpc-formula", "ptpc-usage-duration"] },
  { id: 82, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Прежде чем его повысили, он работал ассистентом три года.", correctAnswer: "Before he was promoted, he had been working as an assistant for three years", explanation: "Before + PS (was promoted), PPC (had been working). Работал ассистентом три года.", hintIds: ["ptpc-signal-before", "ptpc-usage-duration"] },
  { id: 83, tense: "past-perfect-continuous", type: "translate_ru_en", question: "После того как она плакала весь вечер, она наконец уснула.", correctAnswer: "After she had been crying all evening, she finally fell asleep", explanation: "After + PPC (had been crying), PS (fell asleep). Плакала весь вечер.", hintIds: ["ptpc-formula", "ptpc-signal-all"] },
  // Negative PPC
  { id: 84, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Она не спала хорошо до того, как сменила матрас.", correctAnswer: "She hadn't been sleeping well before she changed her mattress", explanation: "Past Perfect Continuous отрицание: hadn't been sleeping. Плохо спала до смены матраса.", hintIds: ["ptpc-negative", "ptpc-signal-before"] },
  { id: 85, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Они не тренировались достаточно перед соревнованиями.", correctAnswer: "They hadn't been training enough before the competition", explanation: "Past Perfect Continuous отрицание: hadn't been training. Недостаточно тренировались.", hintIds: ["ptpc-negative", "ptpc-usage-visible-result"] },
  { id: 86, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Он не питался правильно неделями до того, как попал в больницу.", correctAnswer: "He hadn't been eating properly for weeks before he ended up in hospital", explanation: "Past Perfect Continuous отрицание: hadn't been eating. Недостаточно ел недели.", hintIds: ["ptpc-negative", "ptpc-usage-duration"] },
  // for/since duration
  { id: 87, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Она преподавала в этой школе двадцать лет до выхода на пенсию.", correctAnswer: "She had been teaching at that school for twenty years before she retired", explanation: "For + период → PPC: had been teaching for twenty years.", hintIds: ["ptpc-signal-for", "ptpc-usage-duration"] },
  { id: 88, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Он жил в Москве с 2005 года до переезда в Санкт-Петербург.", correctAnswer: "He had been living in Moscow since 2005 before he moved to St Petersburg", explanation: "Since + точка отсчёта → PPC: had been living since 2005.", hintIds: ["ptpc-signal-since", "ptpc-usage-duration"] },
  { id: 89, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Они встречались пять лет, прежде чем поженились.", correctAnswer: "They had been dating for five years before they got married", explanation: "For + период → PPC: had been dating for five years.", hintIds: ["ptpc-signal-for", "ptpc-usage-duration"] },
  // PPC vs PP (choose correct based on context)
  { id: 90, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Она запыхалась, потому что бежала. (процесс)", correctAnswer: "She was out of breath because she had been running", explanation: "Видимый результат процесса → PPC: had been running. Важен процесс бега, который привёл к результату.", hintIds: ["ptpc-vs-past-perfect", "ptpc-usage-visible-result"] },
  { id: 91, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Она пробежала марафон к вечеру. (результат)", correctAnswer: "She had run the marathon by the evening", explanation: "Результат завершён (пробежала марафон) → Past Perfect: had run. Важен результат, а не процесс.", hintIds: ["ptpc-vs-past-perfect", "ptpc-usage-visible-result"] },
  { id: 92, tense: "past-perfect-continuous", type: "translate_ru_en", question: "У неё были красные глаза, потому что она плакала. (процесс)", correctAnswer: "Her eyes were red because she had been crying", explanation: "Видимый результат длительного процесса (красные глаза от плача) → PPC: had been crying.", hintIds: ["ptpc-vs-past-perfect", "ptpc-usage-visible-result"] },
  // Stative verb situations (use PP not PPC)
  { id: 93, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Она знала его десять лет до того, как они поженились.", correctAnswer: "She had known him for ten years before they got married", explanation: "Know — stative verb, не используется в Continuous. Past Perfect: had known.", hintIds: ["ptpc-stative", "ptpc-stative-list"] },
  { id: 94, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Он верил этой истории долгое время, прежде чем узнал правду.", correctAnswer: "He had believed that story for a long time before he learnt the truth", explanation: "Believe — stative verb, не используется в Continuous. Past Perfect: had believed.", hintIds: ["ptpc-stative", "ptpc-stative-list"] },
  { id: 95, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Они владели этим домом с 1990 года до продажи.", correctAnswer: "They had owned the house since 1990 before they sold it", explanation: "Own — stative verb, не используется в Continuous. Past Perfect: had owned.", hintIds: ["ptpc-stative", "ptpc-stative-list"] },
  // Mixed/complex sentences
  { id: 96, tense: "past-perfect-continuous", type: "translate_ru_en", question: "К тому времени как пожарные прибыли, огонь горел уже три часа.", correctAnswer: "By the time the firefighters arrived, the fire had been burning for three hours", explanation: "By the time + PS (arrived), PPC (had been burning). Огонь горел три часа.", hintIds: ["ptpc-signal-by-the-time", "ptpc-usage-duration"] },
  { id: 97, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Он не готовился к экзамену, поэтому провалил его.", correctAnswer: "He hadn't been preparing for the exam, so he failed it", explanation: "PPC отрицание: hadn't been preparing. Не готовился, поэтому провалил — видимый результат.", hintIds: ["ptpc-negative", "ptpc-usage-visible-result"] },
  { id: 98, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Как долго ты ждал, прежде чем автобус приехал?", correctAnswer: "How long had you been waiting before the bus came", explanation: "Wh-вопрос: How long + had + you + been + V-ing?", hintIds: ["ptpc-wh-question", "ptpc-signal-how-long"] },
  { id: 99, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Мальчик плавал целый час, прежде чем его позвали обедать. (удвойте согласную)", correctAnswer: "The boy had been swimming for an hour before he was called for lunch", explanation: "Swim → swimming (удвоение m). PPC: had been swimming.", hintIds: ["ptpc-spelling-double", "ptpc-formula"] },
  { id: 100, tense: "past-perfect-continuous", type: "translate_ru_en", question: "Она лежала на пляже всё утро, прежде чем начался дождь. (ie → y)", correctAnswer: "She had been lying on the beach all morning before it started raining", explanation: "Lie → lying (ie → y). PPC: had been lying. Лежала на пляже всё утро.", hintIds: ["ptpc-spelling-ing", "ptpc-signal-all"] },
];
