import type { Exercise } from "@/lib/tutor-data";

// ============================================================
// Past Perfect — 100 exercises
// ============================================================

export const pastPerfectExercises: Exercise[] = [
  // ===== Multiple Choice (1–36) =====
  // Basic had + V3 (regular verbs)
  { id: 1, tense: "past-perfect", type: "multiple_choice", question: "She ___ her homework before dinner.", options: ["had finished", "has finished", "finished", "had finish"], correctAnswer: "had finished", explanation: "Past Perfect: had + V3. Действие произошло раньше другого действия в прошлом (before dinner).", hintIds: ["ptp-formula", "ptp-signal-before"] },
  { id: 2, tense: "past-perfect", type: "multiple_choice", question: "By 6 pm, he ___ all his work.", options: ["had worked", "has worked", "worked", "had work"], correctAnswer: "had worked", explanation: "By + момент в прошлом → Past Perfect: had + V3.", hintIds: ["ptp-formula", "ptp-signal-by"] },
  { id: 3, tense: "past-perfect", type: "multiple_choice", question: "When I arrived, she ___ the room.", options: ["had cleaned", "has cleaned", "cleaned", "had clean"], correctAnswer: "had cleaned", explanation: "Когда я пришёл (Past Simple), она уже убрала (Past Perfect). PP показывает, что действие произошло раньше.", hintIds: ["ptp-formula", "ptp-usage-precedence"] },
  { id: 4, tense: "past-perfect", type: "multiple_choice", question: "He ___ a delicious meal before the guests arrived.", options: ["had cooked", "has cooked", "cooked", "had cook"], correctAnswer: "had cooked", explanation: "Past Perfect: had + V3. Приготовил до того, как гости пришли.", hintIds: ["ptp-formula", "ptp-signal-before"] },
  { id: 5, tense: "past-perfect", type: "multiple_choice", question: "The film ___ by the time we got to the cinema.", options: ["had started", "has started", "started", "had start"], correctAnswer: "had started", explanation: "By the time + Past Simple → Past Perfect в главной части: had started.", hintIds: ["ptp-formula", "ptp-signal-by-the-time"] },
  // had + V3 (irregular verbs)
  { id: 6, tense: "past-perfect", type: "multiple_choice", question: "She ___ to the shop before I woke up.", options: ["had gone", "has gone", "went", "had go"], correctAnswer: "had gone", explanation: "Go — неправильный глагол: go → went → gone. Past Perfect: had gone.", hintIds: ["ptp-formula", "ptp-usage-precedence"] },
  { id: 7, tense: "past-perfect", type: "multiple_choice", question: "I ___ that film before, so I didn't want to watch it again.", options: ["had seen", "has seen", "saw", "had see"], correctAnswer: "had seen", explanation: "See — неправильный: see → saw → seen. Увидел раньше (до второго действия).", hintIds: ["ptp-formula", "ptp-usage-precedence"] },
  { id: 8, tense: "past-perfect", type: "multiple_choice", question: "He ___ the letter before he left the office.", options: ["had written", "has written", "wrote", "had write"], correctAnswer: "had written", explanation: "Write — неправильный: write → wrote → written. Past Perfect: had written.", hintIds: ["ptp-formula", "ptp-signal-before"] },
  { id: 9, tense: "past-perfect", type: "multiple_choice", question: "They ___ lunch before the meeting started.", options: ["had eaten", "has eaten", "ate", "had eat"], correctAnswer: "had eaten", explanation: "Eat — неправильный: eat → ate → eaten. Пообедали до начала собрания.", hintIds: ["ptp-formula", "ptp-signal-before"] },
  { id: 10, tense: "past-perfect", type: "multiple_choice", question: "By the time I called, she already ___.", options: ["had left", "has left", "left", "had leave"], correctAnswer: "had left", explanation: "Leave — неправильный: leave → left → left. Already + by the time → had left.", hintIds: ["ptp-formula", "ptp-signal-by-the-time", "ptp-signal-already"] },
  // Negation
  { id: 11, tense: "past-perfect", type: "multiple_choice", question: "She ___ not ___ her homework when I called.", options: ["had / finished", "has / finished", "was / finished", "did / finish"], correctAnswer: "had / finished", explanation: "Past Perfect отрицание: hadn't + V3. Она ещё не закончила, когда я позвонил.", hintIds: ["ptp-negative", "ptp-usage-precedence"] },
  { id: 12, tense: "past-perfect", type: "multiple_choice", question: "He ___ not ___ the book before the class.", options: ["had / read", "has / read", "was / read", "did / read"], correctAnswer: "had / read", explanation: "Past Perfect отрицание: hadn't + V3. Read — неправильный: read → read → read.", hintIds: ["ptp-negative", "ptp-signal-before"] },
  { id: 13, tense: "past-perfect", type: "multiple_choice", question: "I ___ not ___ that restaurant before last night.", options: ["had / tried", "has / tried", "was / try", "did / try"], correctAnswer: "had / tried", explanation: "Past Perfect отрицание: hadn't + V3. До прошлого вечера я не пробовал.", hintIds: ["ptp-negative", "ptp-signal-never"] },
  // Questions
  { id: 14, tense: "past-perfect", type: "multiple_choice", question: "___ she ___ her homework before dinner?", options: ["Had / finished", "Has / finished", "Did / finish", "Was / finished"], correctAnswer: "Had / finished", explanation: "Вопрос в Past Perfect: Had + подлежащее + V3?", hintIds: ["ptp-question", "ptp-signal-before"] },
  { id: 15, tense: "past-perfect", type: "multiple_choice", question: "___ they ___ before the film started?", options: ["Had / arrived", "Have / arrived", "Did / arrive", "Were / arrived"], correctAnswer: "Had / arrived", explanation: "Вопрос в Past Perfect: Had + подлежащее + V3?", hintIds: ["ptp-question", "ptp-signal-before"] },
  { id: 16, tense: "past-perfect", type: "multiple_choice", question: "___ you ___ the email before he called?", options: ["Had / read", "Have / read", "Did / read", "Were / read"], correctAnswer: "Had / read", explanation: "Вопрос в Past Perfect: Had + you + V3?", hintIds: ["ptp-question", "ptp-usage-precedence"] },
  { id: 17, tense: "past-perfect", type: "multiple_choice", question: "___ he ___ the door before you knocked?", options: ["Had / locked", "Has / locked", "Did / lock", "Was / locked"], correctAnswer: "Had / locked", explanation: "Вопрос в Past Perfect: Had + he + V3?", hintIds: ["ptp-question", "ptp-signal-before"] },
  // Wh-questions
  { id: 18, tense: "past-perfect", type: "multiple_choice", question: "What ___ you ___ before you left the house?", options: ["had / done", "have / done", "did / do", "were / doing"], correctAnswer: "had / done", explanation: "Wh-вопрос в Past Perfect: What + had + подлежащее + V3?", hintIds: ["ptp-wh-question"] },
  { id: 19, tense: "past-perfect", type: "multiple_choice", question: "Where ___ she ___ before she moved to London?", options: ["had / lived", "has / lived", "did / live", "was / living"], correctAnswer: "had / lived", explanation: "Wh-вопрос: Where + had + she + V3?", hintIds: ["ptp-wh-question"] },
  { id: 20, tense: "past-perfect", type: "multiple_choice", question: "Why ___ he not ___ the letter before the meeting?", options: ["had / sent", "has / sent", "did / send", "was / sent"], correctAnswer: "had / sent", explanation: "Why + hadn't + he + V3? Send — неправильный: sent.", hintIds: ["ptp-wh-question", "ptp-negative"] },
  // by the time
  { id: 21, tense: "past-perfect", type: "multiple_choice", question: "By the time we arrived, the concert ___.", options: ["had begun", "has begun", "began", "had begin"], correctAnswer: "had begun", explanation: "By the time + Past Simple → Past Perfect: had begun. Begin — неправильный: begun.", hintIds: ["ptp-signal-by-the-time", "ptp-formula"] },
  { id: 22, tense: "past-perfect", type: "multiple_choice", question: "By the time she got home, it ___ raining.", options: ["had stopped", "has stopped", "stopped", "had stop"], correctAnswer: "had stopped", explanation: "By the time + Past Simple → Past Perfect: had stopped.", hintIds: ["ptp-signal-by-the-time", "ptp-formula"] },
  { id: 23, tense: "past-perfect", type: "multiple_choice", question: "By the time the doctor arrived, the patient ___.", options: ["had died", "has died", "died", "had die"], correctAnswer: "had died", explanation: "By the time + Past Simple → Past Perfect: had died. Die — неправильный: died.", hintIds: ["ptp-signal-by-the-time", "ptp-usage-precedence"] },
  // before / after
  { id: 24, tense: "past-perfect", type: "multiple_choice", question: "After she ___ the email, she turned off the computer.", options: ["had sent", "has sent", "sent", "had send"], correctAnswer: "had sent", explanation: "After + Past Perfect, Past Simple. Сначала отправила, потом выключила.", hintIds: ["ptp-signal-after", "ptp-usage-precedence"] },
  { id: 25, tense: "past-perfect", type: "multiple_choice", question: "Before he ___ to work, he had had breakfast.", options: ["went", "had gone", "goes", "going"], correctAnswer: "went", explanation: "Before + Past Simple, Past Perfect. Глагол before вводит более позднее действие.", hintIds: ["ptp-signal-before", "ptp-usage-precedence"] },
  { id: 26, tense: "past-perfect", type: "multiple_choice", question: "I ___ the washing-up before my parents came home.", options: ["had done", "has done", "did", "had do"], correctAnswer: "had done", explanation: "Сначала сделал (Past Perfect), потом родители пришли (Past Simple).", hintIds: ["ptp-signal-before", "ptp-formula"] },
  // already / just / never
  { id: 27, tense: "past-perfect", type: "multiple_choice", question: "When I got to the station, the train ___ already ___.", options: ["had / left", "has / left", "was / left", "had / leave"], correctAnswer: "had / left", explanation: "Already в Past Perfect: had already + V3. Поезд ушёл до моего прихода.", hintIds: ["ptp-signal-already", "ptp-usage-precedence"] },
  { id: 28, tense: "past-perfect", type: "multiple_choice", question: "She had ___ finished her meal when I arrived.", options: ["just", "yet", "already just", "ever"], correctAnswer: "just", explanation: "Just в Past Perfect ставится между had и V3: had just finished.", hintIds: ["ptp-signal-just"] },
  { id: 29, tense: "past-perfect", type: "multiple_choice", question: "He had never ___ sushi before that day.", options: ["tried", "trying", "try", "tries"], correctAnswer: "tried", explanation: "Never + Past Perfect: had never + V3.", hintIds: ["ptp-signal-never", "ptp-formula"] },
  // until
  { id: 30, tense: "past-perfect", type: "multiple_choice", question: "She ___ not ___ the report until midnight.", options: ["had / finished", "has / finished", "was / finished", "did / finish"], correctAnswer: "had / finished", explanation: "Until + момент в прошлом → Past Perfect отрицание: hadn't finished.", hintIds: ["ptp-signal-until", "ptp-negative"] },
  { id: 31, tense: "past-perfect", type: "multiple_choice", question: "He ___ not ___ until she called him.", options: ["had / left", "has / left", "was / left", "did / leave"], correctAnswer: "had / left", explanation: "Not ... until + Past Simple → Past Perfect: hadn't left.", hintIds: ["ptp-signal-until", "ptp-negative"] },
  // PP vs PS
  { id: 32, tense: "past-perfect", type: "multiple_choice", question: "When I ___ (arrive) at the party, Tom ___ (go) home.", options: ["arrived / had gone", "arrived / went", "had arrived / went", "arrive / had gone"], correctAnswer: "arrived / had gone", explanation: "Последовательность: пришёл (PS), а Том уже ушёл (PP). PP для более раннего действия.", hintIds: ["ptp-usage-precedence", "ptp-vs-past-simple"] },
  // by + time
  { id: 33, tense: "past-perfect", type: "multiple_choice", question: "By 8 o'clock, we ___ dinner.", options: ["had finished", "have finished", "finished", "had finish"], correctAnswer: "had finished", explanation: "By + конкретное время в прошлом → Past Perfect: had finished.", hintIds: ["ptp-signal-by", "ptp-formula"] },
  // NEW: by + time context
  { id: 34, tense: "past-perfect", type: "multiple_choice", question: "By Friday, she ___ all the reports.", options: ["had completed", "has completed", "completed", "had complete"], correctAnswer: "had completed", explanation: "By + день недели в прошлом → Past Perfect: had completed. К пятнице она завершила все отчёты.", hintIds: ["ptp-signal-by", "ptp-formula"] },
  // NEW: PP with stative verbs
  { id: 35, tense: "past-perfect", type: "multiple_choice", question: "By the time I met her, she ___ him for ten years.", options: ["had known", "has known", "knew", "had know"], correctAnswer: "had known", explanation: "Know — stative verb, не используется в Continuous. Past Perfect: had known. Она знала его 10 лет до нашей встречи.", hintIds: ["ptp-stative", "ptp-signal-by-the-time"] },
  // NEW: the first time + PP
  { id: 36, tense: "past-perfect", type: "multiple_choice", question: "It was the first time she ___ sushi.", options: ["had tried", "has tried", "tried", "had try"], correctAnswer: "had tried", explanation: "The first time + Past Perfect описывает отсутствие опыта до того момента. Она никогда раньше не пробовала суши.", hintIds: ["ptp-special-first-time", "ptp-formula"] },

  // ===== Fill in the Blank (37–67) =====
  // Basic had + V3 (affirmative)
  { id: 37, tense: "past-perfect", type: "fill_blank", question: "She ___ (finish) her homework before dinner.", correctAnswer: "had finished", explanation: "Past Perfect: had + V3. Закончила до ужина.", hintIds: ["ptp-formula", "ptp-signal-before"] },
  { id: 38, tense: "past-perfect", type: "fill_blank", question: "He ___ (go) to the shop before I woke up.", correctAnswer: "had gone", explanation: "Go — неправильный: go → went → gone. Past Perfect: had gone.", hintIds: ["ptp-formula", "ptp-usage-precedence"] },
  { id: 39, tense: "past-perfect", type: "fill_blank", question: "I ___ (see) that film before, so I didn't want to watch it again.", correctAnswer: "had seen", explanation: "See — неправильный: see → saw → seen. Past Perfect: had seen.", hintIds: ["ptp-formula", "ptp-usage-precedence"] },
  { id: 40, tense: "past-perfect", type: "fill_blank", question: "They ___ (eat) lunch before the meeting started.", correctAnswer: "had eaten", explanation: "Eat — неправильный: eat → ate → eaten. Past Perfect: had eaten.", hintIds: ["ptp-formula", "ptp-signal-before"] },
  { id: 41, tense: "past-perfect", type: "fill_blank", question: "She ___ (write) the letter before she left.", correctAnswer: "had written", explanation: "Write — неправильный: write → wrote → written. Past Perfect: had written.", hintIds: ["ptp-formula", "ptp-signal-before"] },
  // Negation
  { id: 42, tense: "past-perfect", type: "fill_blank", question: "She ___ (not / finish) her homework when I called.", correctAnswer: "hadn't finished", explanation: "Past Perfect отрицание: hadn't + V3.", hintIds: ["ptp-negative", "ptp-usage-precedence"] },
  { id: 43, tense: "past-perfect", type: "fill_blank", question: "He ___ (not / arrive) when I got to the station.", correctAnswer: "hadn't arrived", explanation: "Past Perfect отрицание: hadn't + V3. Он ещё не пришёл.", hintIds: ["ptp-negative", "ptp-signal-by-the-time"] },
  { id: 44, tense: "past-perfect", type: "fill_blank", question: "I ___ (not / see) that film before last night.", correctAnswer: "hadn't seen", explanation: "Past Perfect отрицание: hadn't + V3. See → seen.", hintIds: ["ptp-negative"] },
  // Questions
  { id: 45, tense: "past-perfect", type: "fill_blank", question: "___ (she / finish) her homework before dinner?", correctAnswer: "Had she finished", explanation: "Вопрос в Past Perfect: Had + подлежащее + V3?", hintIds: ["ptp-question", "ptp-signal-before"] },
  { id: 46, tense: "past-perfect", type: "fill_blank", question: "___ (they / arrive) before the film started?", correctAnswer: "Had they arrived", explanation: "Вопрос в Past Perfect: Had + they + V3?", hintIds: ["ptp-question"] },
  { id: 47, tense: "past-perfect", type: "fill_blank", question: "___ (you / eat) before you went to the cinema?", correctAnswer: "Had you eaten", explanation: "Вопрос в Past Perfect: Had + you + V3?", hintIds: ["ptp-question", "ptp-signal-before"] },
  // Wh-questions
  { id: 48, tense: "past-perfect", type: "fill_blank", question: "What ___ (you / do) before you left the office?", correctAnswer: "had you done", explanation: "Wh-вопрос: What + had + you + V3?", hintIds: ["ptp-wh-question"] },
  { id: 49, tense: "past-perfect", type: "fill_blank", question: "Where ___ (she / go) before she moved to London?", correctAnswer: "had she gone", explanation: "Wh-вопрос: Where + had + she + V3? Go → gone.", hintIds: ["ptp-wh-question"] },
  // by the time (double blanks)
  { id: 50, tense: "past-perfect", type: "fill_blank", question: "By the time I ___ (arrive), she ___ (already / leave).", correctAnswer: "arrived / had already left", explanation: "By the time + PS (arrived), PP (had already left). Сначала ушла, потом я пришёл.", hintIds: ["ptp-signal-by-the-time", "ptp-signal-already"] },
  { id: 51, tense: "past-perfect", type: "fill_blank", question: "By the time we ___ (get) to the station, the train ___ (go).", correctAnswer: "got / had gone", explanation: "By the time + PS (got), PP (had gone). Поезд ушёл раньше.", hintIds: ["ptp-signal-by-the-time", "ptp-usage-precedence"] },
  { id: 52, tense: "past-perfect", type: "fill_blank", question: "By the time she ___ (call), I ___ (already / have) lunch.", correctAnswer: "called / had already had", explanation: "By the time + PS (called), PP (had already had). Had had = принять (еду).", hintIds: ["ptp-signal-by-the-time", "ptp-signal-already"] },
  { id: 53, tense: "past-perfect", type: "fill_blank", question: "By the time he ___ (arrive), everyone ___ (leave).", correctAnswer: "arrived / had left", explanation: "By the time + PS (arrived), PP (had left). Все ушли раньше него.", hintIds: ["ptp-signal-by-the-time", "ptp-usage-precedence"] },
  // before / after
  { id: 54, tense: "past-perfect", type: "fill_blank", question: "Before he ___ (come), I ___ (finish) my work.", correctAnswer: "came / had finished", explanation: "Before + PS (came), PP (had finished). Я закончил раньше его прихода.", hintIds: ["ptp-signal-before", "ptp-usage-precedence"] },
  { id: 55, tense: "past-perfect", type: "fill_blank", question: "After she ___ (read) the book, she ___ (return) it to the library.", correctAnswer: "had read / returned", explanation: "After + PP (had read), PS (returned). Сначала прочитала, потом вернула.", hintIds: ["ptp-signal-after", "ptp-usage-precedence"] },
  // already / just
  { id: 56, tense: "past-perfect", type: "fill_blank", question: "She ___ (already / eat) when I ___ (arrive).", correctAnswer: "had already eaten / arrived", explanation: "Already + PP (had already eaten), PS (arrived). Она уже поела к моему приходу.", hintIds: ["ptp-signal-already", "ptp-usage-precedence"] },
  { id: 57, tense: "past-perfect", type: "fill_blank", question: "She ___ (just / leave) when I ___ (call).", correctAnswer: "had just left / called", explanation: "Just + PP (had just left), PS (called). Она только что ушла к моему звонку.", hintIds: ["ptp-signal-just", "ptp-usage-precedence"] },
  // never / until
  { id: 58, tense: "past-perfect", type: "fill_blank", question: "I ___ (never / try) sushi before that day.", correctAnswer: "had never tried", explanation: "Never + Past Perfect: had never + V3.", hintIds: ["ptp-signal-never", "ptp-formula"] },
  { id: 59, tense: "past-perfect", type: "fill_blank", question: "He ___ (not / finish) the report until midnight.", correctAnswer: "hadn't finished", explanation: "Until + момент → Past Perfect отрицание: hadn't finished.", hintIds: ["ptp-signal-until", "ptp-negative"] },
  // for / since
  { id: 60, tense: "past-perfect", type: "fill_blank", question: "She ___ (work) there for 5 years before she resigned.", correctAnswer: "had worked", explanation: "For + период до момента в прошлом → Past Perfect: had worked.", hintIds: ["ptp-usage-duration"] },
  { id: 61, tense: "past-perfect", type: "fill_blank", question: "He ___ (know) her since 2010 before they got married.", correctAnswer: "had known", explanation: "Since + точка до момента в прошлом → Past Perfect: had known.", hintIds: ["ptp-usage-duration", "ptp-stative"] },
  // had had
  { id: 62, tense: "past-perfect", type: "fill_blank", question: "I ___ (have) a shower before she arrived.", correctAnswer: "had had", explanation: "Have (принять душ) → V3 = had. Past Perfect: had had = принял душ.", hintIds: ["ptp-formula"] },
  // hardly when
  { id: 63, tense: "past-perfect", type: "fill_blank", question: "She ___ (hardly / enter) the room when the phone rang.", correctAnswer: "had hardly entered", explanation: "Hardly + Past Perfect: had hardly + V3 + when + PS.", hintIds: ["ptp-special-hardly-when"] },
  // NEW: by + time with PP
  { id: 64, tense: "past-perfect", type: "fill_blank", question: "By Friday, she ___ (complete) all the reports.", correctAnswer: "had completed", explanation: "By + день недели в прошлом → Past Perfect: had completed.", hintIds: ["ptp-signal-by", "ptp-formula"] },
  // NEW: for/since duration
  { id: 65, tense: "past-perfect", type: "fill_blank", question: "He ___ (live) in Paris for 10 years before he moved to London.", correctAnswer: "had lived", explanation: "For + период до момента в прошлом → Past Perfect: had lived.", hintIds: ["ptp-usage-duration"] },
  // NEW: stative verb in PP
  { id: 66, tense: "past-perfect", type: "fill_blank", question: "She ___ (believe) his story until she saw the evidence.", correctAnswer: "had believed", explanation: "Believe — stative verb, не используется в Continuous. Past Perfect: had believed. Верила до того, как увидела доказательства.", hintIds: ["ptp-stative", "ptp-signal-until"] },
  // NEW: no sooner...than
  { id: 67, tense: "past-perfect", type: "fill_blank", question: "He ___ (no sooner / finish) the report than the boss called.", correctAnswer: "had no sooner finished", explanation: "No sooner + Past Perfect + than + Past Simple: had no sooner finished than the boss called.", hintIds: ["ptp-special-hardly-when"] },

  // ===== Translate RU → EN (68–100) =====
  // Basic PP
  { id: 68, tense: "past-perfect", type: "translate_ru_en", question: "Я уже закончил работу.", correctAnswer: "I had already finished work", explanation: "Already + Past Perfect: had already finished. Результат до другого действия в прошлом.", hintIds: ["ptp-signal-already", "ptp-formula"] },
  { id: 69, tense: "past-perfect", type: "translate_ru_en", question: "Она ушла до моего прихода.", correctAnswer: "She had left before I arrived", explanation: "Действие раньше другого → Past Perfect (had left) + before + Past Simple.", hintIds: ["ptp-signal-before", "ptp-usage-precedence"] },
  { id: 70, tense: "past-perfect", type: "translate_ru_en", question: "Они никогда не видели снега до этой зимы.", correctAnswer: "They had never seen snow before that winter", explanation: "Never + Past Perfect: had never seen. До этой зимы — момент в прошлом.", hintIds: ["ptp-signal-never", "ptp-formula"] },
  { id: 71, tense: "past-perfect", type: "translate_ru_en", question: "К тому времени поезд ушёл.", correctAnswer: "By that time the train had left", explanation: "By that time → Past Perfect: had left.", hintIds: ["ptp-signal-by", "ptp-formula"] },
  { id: 72, tense: "past-perfect", type: "translate_ru_en", question: "Я потерял ключи до того, как понял.", correctAnswer: "I had lost my keys before I realised", explanation: "Before + Past Perfect / Past Simple: had lost до realised.", hintIds: ["ptp-signal-before", "ptp-usage-precedence"] },
  // by the time
  { id: 73, tense: "past-perfect", type: "translate_ru_en", question: "К тому времени как я пришёл, фильм уже начался.", correctAnswer: "By the time I arrived, the film had already started", explanation: "By the time + PS (arrived), PP (had started). Already emphasises prior completion.", hintIds: ["ptp-signal-by-the-time", "ptp-signal-already"] },
  { id: 74, tense: "past-perfect", type: "translate_ru_en", question: "К тому времени как мы добрались до станции, поезд ушёл.", correctAnswer: "By the time we got to the station, the train had left", explanation: "By the time + PS (got), PP (had left).", hintIds: ["ptp-signal-by-the-time", "ptp-usage-precedence"] },
  { id: 75, tense: "past-perfect", type: "translate_ru_en", question: "К тому времени как она позвонила, я уже пообедал.", correctAnswer: "By the time she called, I had already had lunch", explanation: "By the time + PS (called), PP (had already had). Had had = принять еду.", hintIds: ["ptp-signal-by-the-time", "ptp-signal-already"] },
  { id: 76, tense: "past-perfect", type: "translate_ru_en", question: "К тому времени как он пришёл, все уже ушли.", correctAnswer: "By the time he arrived, everyone had already left", explanation: "By the time + PS (arrived), PP (had left).", hintIds: ["ptp-signal-by-the-time", "ptp-signal-already"] },
  { id: 77, tense: "past-perfect", type: "translate_ru_en", question: "By the time he arrived, everyone had left.", correctAnswer: "By the time he arrived, everyone had left", explanation: "By the time + PS, PP. Все ушли раньше него.", hintIds: ["ptp-signal-by-the-time", "ptp-usage-precedence"] },
  // before / after
  { id: 78, tense: "past-perfect", type: "translate_ru_en", question: "Она закончила работу до того, как пошла домой.", correctAnswer: "She had finished work before she went home", explanation: "Before + PS (went), PP (had finished). Сначала закончила, потом пошла.", hintIds: ["ptp-signal-before", "ptp-usage-precedence"] },
  { id: 79, tense: "past-perfect", type: "translate_ru_en", question: "После того как он позавтракал, он пошёл на работу.", correctAnswer: "After he had had breakfast, he went to work", explanation: "After + PP (had had breakfast), PS (went). Had had = позавтракал.", hintIds: ["ptp-signal-after", "ptp-usage-precedence"] },
  { id: 80, tense: "past-perfect", type: "translate_ru_en", question: "Я пришёл до того, как начался дождь.", correctAnswer: "I had arrived before the rain started", explanation: "Before + PS (started), PP (had arrived).", hintIds: ["ptp-signal-before", "ptp-usage-precedence"] },
  { id: 81, tense: "past-perfect", type: "translate_ru_en", question: "После того как она прочитала книгу, она сдала её в библиотеку.", correctAnswer: "After she had read the book, she returned it to the library", explanation: "After + PP (had read), PS (returned).", hintIds: ["ptp-signal-after", "ptp-usage-precedence"] },
  { id: 82, tense: "past-perfect", type: "translate_ru_en", question: "Он уехал до того, как я успел попрощаться.", correctAnswer: "He had left before I had a chance to say goodbye", explanation: "Before + PS, PP. Уехал раньше.", hintIds: ["ptp-signal-before", "ptp-usage-precedence"] },
  // already / just
  { id: 83, tense: "past-perfect", type: "translate_ru_en", question: "Когда я проснулся, дождь уже закончился.", correctAnswer: "When I woke up, the rain had already stopped", explanation: "Already + Past Perfect: had already stopped. Закончился до того, как я проснулся.", hintIds: ["ptp-signal-already", "ptp-usage-precedence"] },
  { id: 84, tense: "past-perfect", type: "translate_ru_en", question: "Она только что ушла, когда я позвонил.", correctAnswer: "She had just left when I called", explanation: "Just + Past Perfect: had just left. Только что ушла к моменту звонка.", hintIds: ["ptp-signal-just", "ptp-usage-precedence"] },
  { id: 85, tense: "past-perfect", type: "translate_ru_en", question: "Они уже забронировали билеты.", correctAnswer: "They had already booked the tickets", explanation: "Already + Past Perfect: had already booked.", hintIds: ["ptp-signal-already", "ptp-formula"] },
  // never / until
  { id: 86, tense: "past-perfect", type: "translate_ru_en", question: "Я никогда не пробовал суши до того дня.", correctAnswer: "I had never tried sushi before that day", explanation: "Never + Past Perfect: had never tried.", hintIds: ["ptp-signal-never", "ptp-formula"] },
  { id: 87, tense: "past-perfect", type: "translate_ru_en", question: "Он не закончил работу до полуночи.", correctAnswer: "He hadn't finished work until midnight", explanation: "Until + момент → Past Perfect отрицание: hadn't finished.", hintIds: ["ptp-signal-until", "ptp-negative"] },
  // for / since
  { id: 88, tense: "past-perfect", type: "translate_ru_en", question: "Она работала там 5 лет до того, как уволилась.", correctAnswer: "She had worked there for 5 years before she resigned", explanation: "For + период до момента в прошлом → Past Perfect: had worked.", hintIds: ["ptp-usage-duration", "ptp-signal-before"] },
  { id: 89, tense: "past-perfect", type: "translate_ru_en", question: "Он знал её с 2010 года.", correctAnswer: "He had known her since 2010", explanation: "Since + точка до момента в прошлом → Past Perfect: had known.", hintIds: ["ptp-usage-duration", "ptp-stative"] },
  // had had
  { id: 90, tense: "past-perfect", type: "translate_ru_en", question: "Я уже принял душ, когда она пришла.", correctAnswer: "I had already had a shower when she arrived", explanation: "Have a shower → V3 = had. PP: had already had = уже принял.", hintIds: ["ptp-signal-already", "ptp-formula"] },
  { id: 91, tense: "past-perfect", type: "translate_ru_en", question: "У него было достаточно времени.", correctAnswer: "He had had enough time", explanation: "Have (иметь) → V3 = had. PP: had had = имел.", hintIds: ["ptp-formula", "ptp-stative"] },
  // PP vs PS context
  { id: 92, tense: "past-perfect", type: "translate_ru_en", question: "Проснувшись, я обнаружил, что кто-то уже съел мой завтрак.", correctAnswer: "When I woke up, I found that someone had eaten my breakfast", explanation: "Кто-то съел (PP) до того, как я проснулся (PS). PP для более раннего действия.", hintIds: ["ptp-usage-precedence", "ptp-vs-past-simple"] },
  { id: 93, tense: "past-perfect", type: "translate_ru_en", question: "Он позвонил мне вчера вечером.", correctAnswer: "He called me yesterday evening", explanation: "Yesterday evening = конкретное время → Past Simple. Нет второго действия в прошлом, поэтому PP не нужен.", hintIds: ["ptp-vs-past-simple", "ptp-no-specific-time"] },
  // hardly / no sooner
  { id: 94, tense: "past-perfect", type: "translate_ru_en", question: "Она едва вошла в комнату, когда зазвонил телефон.", correctAnswer: "She had hardly entered the room when the phone rang", explanation: "Hardly + PP + when + PS: had hardly entered when the phone rang.", hintIds: ["ptp-special-hardly-when"] },
  { id: 95, tense: "past-perfect", type: "translate_ru_en", question: "Он не успел закончить, как босс позвонил.", correctAnswer: "He had hardly finished when the boss called", explanation: "Hardly + PP + when + PS: had hardly finished when the boss called.", hintIds: ["ptp-special-hardly-when"] },
  // Mixed
  { id: 96, tense: "past-perfect", type: "translate_ru_en", question: "К тому времени как я начал изучать английский, мой друг уже говорил на нём fluently.", correctAnswer: "By the time I started learning English, my friend had already been speaking it fluently", explanation: "By the time + PS (started), PP (had already been speaking). Более раннее длительное действие → Past Perfect Continuous.", hintIds: ["ptp-signal-by-the-time", "ptp-signal-already", "ptp-usage-precedence"] },
  // NEW: К тому времени как я пришёл, они уже закончили.
  { id: 97, tense: "past-perfect", type: "translate_ru_en", question: "К тому времени как я пришёл, они уже закончили.", correctAnswer: "By the time I arrived, they had already finished", explanation: "By the time + PS (arrived), PP (had already finished). Они завершили до моего прихода.", hintIds: ["ptp-signal-by-the-time", "ptp-signal-already"] },
  // NEW: Это был первый раз, когда он посетил этот город.
  { id: 98, tense: "past-perfect", type: "translate_ru_en", question: "Это был первый раз, когда он посетил этот город.", correctAnswer: "It was the first time he had visited this city", explanation: "The first time + Past Perfect: had visited. До этого момента он никогда там не был.", hintIds: ["ptp-special-first-time"] },
  // NEW: К пяти часам она уже приготовила ужин.
  { id: 99, tense: "past-perfect", type: "translate_ru_en", question: "К пяти часам она уже приготовила ужин.", correctAnswer: "By five o'clock she had already cooked dinner", explanation: "By + время → Past Perfect: had already cooked. К указанному моменту ужин был готов.", hintIds: ["ptp-signal-by", "ptp-signal-already"] },
  // NEW: Я не успел допить кофе, когда она вошла.
  { id: 100, tense: "past-perfect", type: "translate_ru_en", question: "Я не успел допить кофе, когда она вошла.", correctAnswer: "I had hardly finished my coffee when she came in", explanation: "Hardly + Past Perfect + when + Past Simple: had hardly finished when she came in. Действие едва началось/завершилось, как произошло другое.", hintIds: ["ptp-special-hardly-when"] },
];
