import type { Exercise } from "@/lib/tutor-data";

// ============================================================
// Present Simple — 100 exercises
// ============================================================

export const presentSimpleExercises: Exercise[] = [
  // ---- Multiple Choice (1–35) ----
  { id: 1, tense: "present-simple", type: "multiple_choice", question: "She ___ to school every day.", options: ["go", "goes", "is going", "going"], correctAnswer: "goes", explanation: "3-е лицо (she) + every day → V-s: goes." },
  { id: 2, tense: "present-simple", type: "multiple_choice", question: "The sun ___ in the east.", options: ["rise", "rises", "is rising", "rose"], correctAnswer: "rises", explanation: "Закон природы → Present Simple. Sun = it → rises." },
  { id: 3, tense: "present-simple", type: "multiple_choice", question: "They ___ tea every morning.", options: ["drinks", "drink", "are drinking", "drank"], correctAnswer: "drink", explanation: "They → множественное число → V1 без изменений: drink." },
  { id: 4, tense: "present-simple", type: "multiple_choice", question: "He ___ not like coffee.", options: ["do", "does", "is", "has"], correctAnswer: "does", explanation: "He = 3-е лицо → does not + V1." },
  { id: 5, tense: "present-simple", type: "multiple_choice", question: "___ you speak French?", options: ["Do", "Does", "Are", "Is"], correctAnswer: "Do", explanation: "Вопрос к You → Do + you + V1?" },
  { id: 6, tense: "present-simple", type: "multiple_choice", question: "My brother ___ in London.", options: ["live", "lives", "is living", "has lived"], correctAnswer: "lives", explanation: "Факт о месте жительства. Brother = he → lives." },
  { id: 7, tense: "present-simple", type: "multiple_choice", question: "Water ___ at 100 degrees Celsius.", options: ["boil", "boils", "is boiling", "boiled"], correctAnswer: "boils", explanation: "Научный факт. Water = it → boils." },
  { id: 8, tense: "present-simple", type: "multiple_choice", question: "I ___ a teacher.", options: ["am", "is", "are", "do"], correctAnswer: "am", explanation: "Глагол to be: I am." },
  { id: 9, tense: "present-simple", type: "multiple_choice", question: "The train ___ at 6 pm.", options: ["leave", "leaves", "is leaving", "left"], correctAnswer: "leaves", explanation: "Расписание → Present Simple. Train = it → leaves." },
  { id: 10, tense: "present-simple", type: "multiple_choice", question: "She always ___ the bus to work.", options: ["catch", "catches", "is catching", "caught"], correctAnswer: "catches", explanation: "She + always → V+es. Глагол на -ch → catches." },
  { id: 11, tense: "present-simple", type: "multiple_choice", question: "We ___ dinner at 7 pm.", options: ["have", "has", "are having", "had"], correctAnswer: "have", explanation: "We → V1 без изменений: have dinner." },
  { id: 12, tense: "present-simple", type: "multiple_choice", question: "He ___ his teeth twice a day.", options: ["brush", "brushes", "is brushing", "brushed"], correctAnswer: "brushes", explanation: "He + twice a day → brushes. На -sh → +es." },
  { id: 13, tense: "present-simple", type: "multiple_choice", question: "The film ___ at 8 o'clock.", options: ["start", "starts", "is starting", "started"], correctAnswer: "starts", explanation: "Расписание → Film = it → starts." },
  { id: 14, tense: "present-simple", type: "multiple_choice", question: "I ___ not understand this rule.", options: ["do", "does", "am", "don't"], correctAnswer: "don't", explanation: "Отрицание для I → I do not (don't) understand." },
  { id: 15, tense: "present-simple", type: "multiple_choice", question: "___ she work in a hospital?", options: ["Do", "Does", "Is", "Are"], correctAnswer: "Does", explanation: "Вопрос к she → Does + she + V1?" },
  { id: 16, tense: "present-simple", type: "multiple_choice", question: "Cats ___ milk.", options: ["like", "likes", "are liking", "liked"], correctAnswer: "like", explanation: "Cats = множественное число → V1: like." },
  { id: 17, tense: "present-simple", type: "multiple_choice", question: "He ___ to the gym three times a week.", options: ["go", "goes", "is going", "went"], correctAnswer: "goes", explanation: "He + three times a week → goes." },
  { id: 18, tense: "present-simple", type: "multiple_choice", question: "My parents ___ in a small town.", options: ["live", "lives", "are living", "lived"], correctAnswer: "live", explanation: "Parents = множественное число → live." },
  { id: 19, tense: "present-simple", type: "multiple_choice", question: "She ___ a shower every evening.", options: ["take", "takes", "is taking", "took"], correctAnswer: "takes", explanation: "She = 3-е лицо → takes." },
  { id: 20, tense: "present-simple", type: "multiple_choice", question: "I've ___ a dog.", options: ["get", "got", "getting", "gets"], correctAnswer: "got", explanation: "Британский вариант: I've got = у меня есть." },
  { id: 21, tense: "present-simple", type: "multiple_choice", question: "The shop ___ at 9 am and ___ at 6 pm.", options: ["open/close", "opens/closes", "is opening/is closing", "opened/closed"], correctAnswer: "opens/closes", explanation: "Расписание → Shop = it → opens/closes." },
  { id: 22, tense: "present-simple", type: "multiple_choice", question: "He ___ never late for work.", options: ["is", "are", "do", "does"], correctAnswer: "is", explanation: "Глагол to be: He is never late." },
  { id: 23, tense: "present-simple", type: "multiple_choice", question: "___ they have a car?", options: ["Do", "Does", "Are", "Have"], correctAnswer: "Do", explanation: "Вопрос к they → Do they have?" },
  { id: 24, tense: "present-simple", type: "multiple_choice", question: "It ___ a lot in winter in London.", options: ["snow", "snows", "is snowing", "snowed"], correctAnswer: "snows", explanation: "Регулярное явление → It = snows." },
  { id: 25, tense: "present-simple", type: "multiple_choice", question: "She ___ French and Spanish.", options: ["speak", "speaks", "is speaking", "spoke"], correctAnswer: "speaks", explanation: "She = 3-е лицо → speaks." },
  { id: 26, tense: "present-simple", type: "multiple_choice", question: "I usually ___ up at 7 am.", options: ["wake", "wakes", "am waking", "woke"], correctAnswer: "wake", explanation: "I + usually → V1: wake." },
  { id: 27, tense: "present-simple", type: "multiple_choice", question: "He ___ mathematics at university.", options: ["study", "studies", "is studying", "studied"], correctAnswer: "studies", explanation: "He + study → studies (согласная + y → ies)." },
  { id: 28, tense: "present-simple", type: "multiple_choice", question: "Birds ___ south in autumn.", options: ["fly", "flies", "are flying", "flew"], correctAnswer: "fly", explanation: "Birds = множественное → fly." },
  { id: 29, tense: "present-simple", type: "multiple_choice", question: "She ___ her homework after school.", options: ["do", "does", "is doing", "did"], correctAnswer: "does", explanation: "She = 3-е лицо → does." },
  { id: 30, tense: "present-simple", type: "multiple_choice", question: "He ___ a taxi to work every day.", options: ["take", "takes", "is taking", "took"], correctAnswer: "takes", explanation: "He = 3-е лицо → takes." },
  { id: 31, tense: "present-simple", type: "multiple_choice", question: "We ___ not go to school on Sundays.", options: ["do", "does", "are", "don't"], correctAnswer: "don't", explanation: "Отрицание для We: We do not go." },
  { id: 32, tense: "present-simple", type: "multiple_choice", question: "The Earth ___ around the Sun.", options: ["go", "goes", "is going", "went"], correctAnswer: "goes", explanation: "Закон природы. Earth = it → goes." },
  { id: 33, tense: "present-simple", type: "multiple_choice", question: "My sister ___ very well.", options: ["cook", "cooks", "is cooking", "cooked"], correctAnswer: "cooks", explanation: "Sister = she → cooks." },
  { id: 34, tense: "present-simple", type: "multiple_choice", question: "He ___ his wallet everywhere.", options: ["carry", "carries", "is carrying", "carried"], correctAnswer: "carries", explanation: "He + carry → carries (согласная + y → ies)." },
  { id: 35, tense: "present-simple", type: "multiple_choice", question: "I ___ you are right.", options: ["think", "thinks", "am thinking", "thought"], correctAnswer: "think", explanation: "Think (мнение) = stative verb → I think." },

  // ---- Fill in the Blank (36–65) ----
  { id: 36, tense: "present-simple", type: "fill_blank", question: "She ___ (go) to the gym every morning.", correctAnswer: "goes", explanation: "She = 3-е лицо → goes." },
  { id: 37, tense: "present-simple", type: "fill_blank", question: "They ___ (not / work) on Saturdays.", correctAnswer: "don't work", explanation: "They → don't + V1." },
  { id: 38, tense: "present-simple", type: "fill_blank", question: "He ___ (study) English every day.", correctAnswer: "studies", explanation: "He + study → studies (согласная + y → ies)." },
  { id: 39, tense: "present-simple", type: "fill_blank", question: "___ (you / like) chocolate?", correctAnswer: "Do you like", explanation: "Вопрос: Do you like?" },
  { id: 40, tense: "present-simple", type: "fill_blank", question: "The bus ___ (arrive) at 10 am.", correctAnswer: "arrives", explanation: "Расписание. Bus = it → arrives." },
  { id: 41, tense: "present-simple", type: "fill_blank", question: "She ___ (wash) her hair every other day.", correctAnswer: "washes", explanation: "She + wash → washes (на -sh → +es)." },
  { id: 42, tense: "present-simple", type: "fill_blank", question: "I ___ (not / understand) this rule.", correctAnswer: "don't understand", explanation: "I → don't + V1." },
  { id: 43, tense: "present-simple", type: "fill_blank", question: "He ___ (carry) a heavy bag.", correctAnswer: "carries", explanation: "He + carry → carries (согласная + y → ies)." },
  { id: 44, tense: "present-simple", type: "fill_blank", question: "___ (she / have) any brothers?", correctAnswer: "Does she have", explanation: "Вопрос к she: Does she have?" },
  { id: 45, tense: "present-simple", type: "fill_blank", question: "My father ___ (drive) to work.", correctAnswer: "drives", explanation: "Father = he → drives." },
  { id: 46, tense: "present-simple", type: "fill_blank", question: "The children ___ (play) in the garden.", correctAnswer: "play", explanation: "Children = множественное → play." },
  { id: 47, tense: "present-simple", type: "fill_blank", question: "She ___ (watch) TV every evening.", correctAnswer: "watches", explanation: "She + watch → watches (на -ch → +es)." },
  { id: 48, tense: "present-simple", type: "fill_blank", question: "He ___ (not / know) the answer.", correctAnswer: "doesn't know", explanation: "He → doesn't + V1." },
  { id: 49, tense: "present-simple", type: "fill_blank", question: "___ (they / live) in London?", correctAnswer: "Do they live", explanation: "Вопрос: Do they live?" },
  { id: 50, tense: "present-simple", type: "fill_blank", question: "My mother ___ (make) delicious cakes.", correctAnswer: "makes", explanation: "Mother = she → makes." },
  { id: 51, tense: "present-simple", type: "fill_blank", question: "He ___ (miss) the bus sometimes.", correctAnswer: "misses", explanation: "He + miss → misses (на -ss → +es)." },
  { id: 52, tense: "present-simple", type: "fill_blank", question: "I've ___ (have) two sisters.", correctAnswer: "got", explanation: "Британский вариант: I've got." },
  { id: 53, tense: "present-simple", type: "fill_blank", question: "She ___ (not / want) to go out.", correctAnswer: "doesn't want", explanation: "She → doesn't + V1." },
  { id: 54, tense: "present-simple", type: "fill_blank", question: "He ___ (teach) mathematics at school.", correctAnswer: "teaches", explanation: "He + teach → teaches (на -ch → +es)." },
  { id: 55, tense: "present-simple", type: "fill_blank", question: "We ___ (usually / eat) lunch at noon.", correctAnswer: "usually eat", explanation: "We + usually → V1: eat." },
  { id: 56, tense: "present-simple", type: "fill_blank", question: "The baby ___ (cry) a lot at night.", correctAnswer: "cries", explanation: "Baby = it + cry → cries (согласная + y → ies)." },
  { id: 57, tense: "present-simple", type: "fill_blank", question: "___ (he / need) help?", correctAnswer: "Does he need", explanation: "Вопрос к he: Does he need?" },
  { id: 58, tense: "present-simple", type: "fill_blank", question: "She ___ (try) to learn Japanese.", correctAnswer: "tries", explanation: "She + try → tries (согласная + y → ies)." },
  { id: 59, tense: "present-simple", type: "fill_blank", question: "I ___ (not / believe) you.", correctAnswer: "don't believe", explanation: "I → don't + V1." },
  { id: 60, tense: "present-simple", type: "fill_blank", question: "He ___ (go) to the office by bus.", correctAnswer: "goes", explanation: "He → goes." },
  { id: 61, tense: "present-simple", type: "fill_blank", question: "The lesson ___ (finish) at 3 pm.", correctAnswer: "finishes", explanation: "Расписание. Lesson = it → finishes (на -sh → +es)." },
  { id: 62, tense: "present-simple", type: "fill_blank", question: "She ___ (not / drink) coffee.", correctAnswer: "doesn't drink", explanation: "She → doesn't + V1." },
  { id: 63, tense: "present-simple", type: "fill_blank", question: "They ___ (enjoy) playing football.", correctAnswer: "enjoy", explanation: "They → V1: enjoy." },
  { id: 64, tense: "present-simple", type: "fill_blank", question: "He ___ (fix) his bike every weekend.", correctAnswer: "fixes", explanation: "He + fix → fixes (на -x → +es)." },
  { id: 65, tense: "present-simple", type: "fill_blank", question: "___ (it / rain) a lot here?", correctAnswer: "Does it rain", explanation: "Вопрос к it: Does it rain?" },

  // ---- Translate RU → EN (66–100) ----
  { id: 66, tense: "present-simple", type: "translate_ru_en", question: "Я работаю в банке.", correctAnswer: "I work in a bank", explanation: "Факт о работе → I work." },
  { id: 67, tense: "present-simple", type: "translate_ru_en", question: "Она пьёт чай каждое утро.", correctAnswer: "She drinks tea every morning", explanation: "Регулярное действие. She → drinks." },
  { id: 68, tense: "present-simple", type: "translate_ru_en", question: "Он не любит кофе.", correctAnswer: "He doesn't like coffee", explanation: "Отрицание: He doesn't like." },
  { id: 69, tense: "present-simple", type: "translate_ru_en", question: "Мы обычно ужинаем в 7 вечера.", correctAnswer: "We usually have dinner at 7 pm", explanation: "Usually → We usually have dinner." },
  { id: 70, tense: "present-simple", type: "translate_ru_en", question: "Ты говоришь по-английски?", correctAnswer: "Do you speak English", explanation: "Вопрос: Do you speak?" },
  { id: 71, tense: "present-simple", type: "translate_ru_en", question: "Солнце встаёт на востоке.", correctAnswer: "The sun rises in the east", explanation: "Закон природы: The sun rises." },
  { id: 72, tense: "present-simple", type: "translate_ru_en", question: "Мой брат живёт в Лондоне.", correctAnswer: "My brother lives in London", explanation: "Brother = he → lives." },
  { id: 73, tense: "present-simple", type: "translate_ru_en", question: "Они не работают по воскресеньям.", correctAnswer: "They don't work on Sundays", explanation: "They don't work on Sundays." },
  { id: 74, tense: "present-simple", type: "translate_ru_en", question: "Поезд отправляется в 6 вечера.", correctAnswer: "The train leaves at 6 pm", explanation: "Расписание: The train leaves." },
  { id: 75, tense: "present-simple", type: "translate_ru_en", question: "Она всегда опаздывает.", correctAnswer: "She is always late", explanation: "Глагол to be: She is always late." },
  { id: 76, tense: "present-simple", type: "translate_ru_en", question: "Я не понимаю.", correctAnswer: "I don't understand", explanation: "I don't understand." },
  { id: 77, tense: "present-simple", type: "translate_ru_en", question: "Он изучает математику в университете.", correctAnswer: "He studies maths at university", explanation: "He + studies. British: maths." },
  { id: 78, tense: "present-simple", type: "translate_ru_en", question: "У меня есть собака.", correctAnswer: "I've got a dog", explanation: "Британский вариант: I've got a dog." },
  { id: 79, tense: "present-simple", type: "translate_ru_en", question: "Мы ходим в кино по пятницам.", correctAnswer: "We go to the cinema on Fridays", explanation: "We go on Fridays." },
  { id: 80, tense: "present-simple", type: "translate_ru_en", question: "Она моет волосы каждый день.", correctAnswer: "She washes her hair every day", explanation: "She + washes (на -sh → +es)." },
  { id: 81, tense: "present-simple", type: "translate_ru_en", question: "Мне нравится музыка.", correctAnswer: "I like music", explanation: "Stative verb like → I like." },
  { id: 82, tense: "present-simple", type: "translate_ru_en", question: "Они играют в футбол после школы.", correctAnswer: "They play football after school", explanation: "They play football after school." },
  { id: 83, tense: "present-simple", type: "translate_ru_en", question: "Он не знает ответа.", correctAnswer: "He doesn't know the answer", explanation: "He doesn't know." },
  { id: 84, tense: "present-simple", type: "translate_ru_en", question: "Моя мама готовит вкусные пироги.", correctAnswer: "My mum cooks delicious pies", explanation: "Mum = she → cooks." },
  { id: 85, tense: "present-simple", type: "translate_ru_en", question: "Вода кипит при 100 градусах.", correctAnswer: "Water boils at 100 degrees", explanation: "Научный факт: Water boils." },
  { id: 86, tense: "present-simple", type: "translate_ru_en", question: "Я всегда встаю рано.", correctAnswer: "I always get up early", explanation: "I always get up." },
  { id: 87, tense: "present-simple", type: "translate_ru_en", question: "Она читает книги перед сном.", correctAnswer: "She reads books before bed", explanation: "She reads books." },
  { id: 88, tense: "present-simple", type: "translate_ru_en", question: "У них есть большая машина.", correctAnswer: "They've got a big car", explanation: "Британский: They've got." },
  { id: 89, tense: "present-simple", type: "translate_ru_en", question: "Он носит очки.", correctAnswer: "He wears glasses", explanation: "He wears glasses." },
  { id: 90, tense: "present-simple", type: "translate_ru_en", question: "Мы редко едим вне дома.", correctAnswer: "We rarely eat out", explanation: "We rarely eat out." },
  { id: 91, tense: "present-simple", type: "translate_ru_en", question: "Когда я приеду, я позвоню тебе.", correctAnswer: "When I arrive, I'll call you", explanation: "When + Present Simple (не will!)." },
  { id: 92, tense: "present-simple", type: "translate_ru_en", question: "Она хочет воды.", correctAnswer: "She wants some water", explanation: "Stative verb: She wants." },
  { id: 93, tense: "present-simple", type: "translate_ru_en", question: "Мне кажется, ты прав.", correctAnswer: "I think you're right", explanation: "Think (мнение) → Present Simple." },
  { id: 94, tense: "present-simple", type: "translate_ru_en", question: "Он работает в больнице.", correctAnswer: "He works in a hospital", explanation: "He works in a hospital." },
  { id: 95, tense: "present-simple", type: "translate_ru_en", question: "Я не вижу разницы.", correctAnswer: "I don't see the difference", explanation: "Stative verb see → I don't see." },
  { id: 96, tense: "present-simple", type: "translate_ru_en", question: "Она хорошо поёт.", correctAnswer: "She sings well", explanation: "She sings well." },
  { id: 97, tense: "present-simple", type: "translate_ru_en", question: "Они всегда помогают друг другу.", correctAnswer: "They always help each other", explanation: "They always help each other." },
  { id: 98, tense: "present-simple", type: "translate_ru_en", question: "Мне нужна помощь.", correctAnswer: "I need help", explanation: "Stative verb need → I need." },
  { id: 99, tense: "present-simple", type: "translate_ru_en", question: "Он играет на пианино каждый день.", correctAnswer: "He plays the piano every day", explanation: "He plays the piano every day." },
  { id: 100, tense: "present-simple", type: "translate_ru_en", question: "Мы любим путешествовать.", correctAnswer: "We love travelling", explanation: "Stative verb love → We love. British: travelling." },
];
