import type { Exercise } from "@/lib/tutor-data";

// ============================================================
// Present Final Test — 100 exercises (Comprehensive Mixed Test)
// ============================================================

export const presentFinalTestExercises: Exercise[] = [
  // ===== Multiple Choice (1–35) =====

  // --- Mixed Tense Selection ---
  { id: 1, tense: "present-final-test", type: "multiple_choice", question: "She ___ coffee every morning, but today she ___ tea.", options: ["drinks / is drinking", "is drinking / drinks", "drank / is drinking", "drinks / drinks"], correctAnswer: "drinks / is drinking", explanation: "Каждое утро = рутина → Present Simple. Но сегодня (отклонение) → Present Continuous.", hintIds: ["ps-signal-routine", "pc-signal-temp", "ps-formula-vs", "pc-formula"] },
  { id: 2, tense: "present-final-test", type: "multiple_choice", question: "I ___ three cups of coffee today and I ___ more right now.", options: ["have drunk / am drinking", "drank / drink", "have been drinking / drink", "drink / am drinking"], correctAnswer: "have drunk / am drinking", explanation: "Today (период не окончен) + количество → Present Perfect. Right now → Present Continuous.", hintIds: ["pp-signal-today", "pc-signal-now", "pp-formula", "pp-irregular"] },
  { id: 3, tense: "present-final-test", type: "multiple_choice", question: "How long ___ you ___ for the bus? — I ___ since 8 am.", options: ["have / been waiting / have been", "have / waited / have", "do / wait / am", "are / waiting / was"], correctAnswer: "have / been waiting / have been", explanation: "How long + ожидание = процесс → Present Perfect Continuous. Since + точка → have been waiting.", hintIds: ["ppc-formula", "ppc-signal-since", "ppc-usage-process"] },
  { id: 4, tense: "present-final-test", type: "multiple_choice", question: "The Prime Minister ___ yesterday. She ___ her resignation.", options: ["resigned / has announced", "has resigned / announced", "resigned / announced", "has resigned / has announced"], correctAnswer: "resigned / has announced", explanation: "Yesterday = конкретное время → Past Simple. She has announced = свежая новость без конкретного времени.", hintIds: ["pp-no-yesterday", "pp-signal-news"] },
  { id: 5, tense: "present-final-test", type: "multiple_choice", question: "He ___ all morning. He ___ very tired now.", options: ["has been running / is", "has run / is", "has been running / has been", "ran / is"], correctAnswer: "has been running / is", explanation: "All morning + результат (устал) → Present Perfect Continuous. Is tired = состояние сейчас.", hintIds: ["ppc-signal-all", "ppc-usage-evidence", "ppc-formula"] },
  { id: 6, tense: "present-final-test", type: "multiple_choice", question: "This is the best pizza I ___.", options: ["have ever eaten", "ever ate", "have ever been eating", "am ever eating"], correctAnswer: "have ever eaten", explanation: "Superlative (the best) + ever → Present Perfect: have ever + V3.", hintIds: ["pp-signal-superlative", "pp-formula", "pp-irregular"] },
  { id: 7, tense: "present-final-test", type: "multiple_choice", question: "We ___ to London next week. We ___ our tickets already.", options: ["are flying / have booked", "fly / booked", "are flying / are booking", "fly / have booked"], correctAnswer: "are flying / have booked", explanation: "Next week (запланировано) → Present Continuous. Already (результат) → Present Perfect.", hintIds: ["pc-usage-planned", "pp-signal-already"] },
  { id: 8, tense: "present-final-test", type: "multiple_choice", question: "She ___ her room since 10 o'clock and she ___ yet.", options: ["has been cleaning / hasn't finished", "has cleaned / isn't finishing", "is cleaning / doesn't finish", "cleaned / hasn't been finishing"], correctAnswer: "has been cleaning / hasn't finished", explanation: "Since + процесс уборки → Present Perfect Continuous. Yet = ещё не → hasn't finished.", hintIds: ["ppc-formula", "ppc-signal-since", "pp-signal-yet"] },
  { id: 9, tense: "present-final-test", type: "multiple_choice", question: "When I ___ home, I ___ you.", options: ["get / will call", "will get / call", "get / call", "will get / will call"], correctAnswer: "get / will call", explanation: "After 'when' в придаточном времени → Present Simple (не will!). Главная часть → will + V1.", hintIds: ["ps-when-if"] },
  { id: 10, tense: "present-final-test", type: "multiple_choice", question: "The train ___ at 6 pm. It ___ at platform 3 right now.", options: ["leaves / is arriving", "leaves / is arriving", "is leaving / arrives", "left / is arriving"], correctAnswer: "leaves / is arriving", explanation: "Расписание → Present Simple (leaves). Прямо сейчас → Present Continuous (is arriving).", hintIds: ["ps-schedule", "pc-signal-now", "ps-formula-v1", "pc-formula"] },

  // --- Stative Verbs ---
  { id: 11, tense: "present-final-test", type: "multiple_choice", question: "I ___ this is a bad idea. I ___ with you.", options: ["think / don't agree", "am thinking / am not agreeing", "think / am not agreeing", "am thinking / don't agree"], correctAnswer: "think / don't agree", explanation: "Think (мнение) и agree — стативные глаголы → Present Simple.", hintIds: ["ps-think-opinion", "ps-stative", "ps-negative"] },
  { id: 12, tense: "present-final-test", type: "multiple_choice", question: "She ___ the soup. It ___ delicious.", options: ["is tasting / tastes", "tastes / is tasting", "tastes / tastes", "is tasting / is tasting"], correctAnswer: "is tasting / tastes", explanation: "Taste = пробовать (действие) → Continuous. Taste = иметь вкус (состояние) → Simple.", hintIds: ["pc-dual-taste", "ps-stative", "pc-formula"] },
  { id: 13, tense: "present-final-test", type: "multiple_choice", question: "I ___ him since 2010. He ___ a kind person.", options: ["have known / is", "have been knowing / is", "know / is being", "am knowing / was"], correctAnswer: "have known / is", explanation: "Know = стативный → Present Perfect (НЕ Continuous!). Is = факт.", hintIds: ["pp-stative", "ppc-no-stative", "pp-signal-since"] },
  { id: 14, tense: "present-final-test", type: "multiple_choice", question: "What ___ you ___ about? — I ___ about my future.", options: ["are / thinking / am thinking", "do / think / think", "are / thinking / think", "do / think / am thinking"], correctAnswer: "are / thinking / am thinking", explanation: "Think = размышлять (процесс) → Present Continuous в обоих случаях.", hintIds: ["pc-dual-think", "pc-formula"] },
  { id: 15, tense: "present-final-test", type: "multiple_choice", question: "She ___ well today. She ___ better now.", options: ["is feeling / is looking", "feels / looks", "is feeling / looks", "feels / is looking"], correctAnswer: "is feeling / looks", explanation: "Feel (самочувствие) → CAN be Continuous. Look (выглядеть) = стативный → Simple.", hintIds: ["pc-dual-taste", "pc-usage-now", "ps-stative"] },
  { id: 16, tense: "present-final-test", type: "multiple_choice", question: "He ___ the doctor tomorrow. He ___ a pain in his back.", options: ["is seeing / has", "sees / is having", "sees / has", "is seeing / is having"], correctAnswer: "is seeing / has", explanation: "See = встречаться (запланировано) → Continuous. Have (испытывать боль) = стативный → Simple.", hintIds: ["pc-dual-see", "pc-dual-have", "pc-usage-planned"] },
  { id: 17, tense: "present-final-test", type: "multiple_choice", question: "I ___ what you mean. I ___ you.", options: ["see / understand", "am seeing / am understanding", "see / am understanding", "am seeing / understand"], correctAnswer: "see / understand", explanation: "See (понимать) и understand — стативные глаголы → Present Simple.", hintIds: ["ps-stative", "pc-no-stative", "ps-formula-v1"] },
  { id: 18, tense: "present-final-test", type: "multiple_choice", question: "The flowers ___ wonderful! She ___ them right now.", options: ["smell / is smelling", "are smelling / smells", "smell / smells", "is smelling / is smelling"], correctAnswer: "smell / is smelling", explanation: "Smell (пахнуть) = стативный → Simple. Smell (нюхать) = действие → Continuous.", hintIds: ["pc-dual-taste", "pc-signal-now", "ps-stative", "pc-formula"] },

  // --- -ing Spelling ---
  { id: 19, tense: "present-final-test", type: "multiple_choice", question: "She's ___ the cake for the party.", options: ["baking", "bakeing", "bakinging", "baking"], correctAnswer: "baking", explanation: "Bake: гласная + согласная + e → убрать e, добавить -ing: baking.", hintIds: ["pc-spelling-drop-e", "pc-formula"] },
  { id: 20, tense: "present-final-test", type: "multiple_choice", question: "He's ___ his suitcase for the trip.", options: ["packing", "packking", "packing", "paccking"], correctAnswer: "packing", explanation: "Pack: краткий гласный + 1 согласная (ck = 2 согласных) → НЕ удваиваем: packing.", hintIds: ["pc-spelling-no-double", "pc-formula"] },
  { id: 21, tense: "present-final-test", type: "multiple_choice", question: "The baby ___ because she's hungry.", options: ["is crying", "is crying", "is cring", "is cryying"], correctAnswer: "is crying", explanation: "Cry: согласная + y. В Continuous: crying (НЕ -yying). Удвоение не требуется.", hintIds: ["pc-spelling-no-double", "pc-formula"] },
  { id: 22, tense: "present-final-test", type: "multiple_choice", question: "She ___ in bed right now.", options: ["is lying", "is lying", "is lieing", "is lyeing"], correctAnswer: "is lying", explanation: "Lie → lying: -ie превращается в -y, потом + -ing. НЕ -lieing.", hintIds: ["pc-spelling-ie", "pc-formula"] },
  { id: 23, tense: "present-final-test", type: "multiple_choice", question: "They ___ to Japan next month.", options: ["are travelling", "are travelinging", "are traveling", "are traveing"], correctAnswer: "are travelling", explanation: "Британский английский: travel → travelling (удвоение l после краткого гласного). НЕ traveling.", hintIds: ["pc-spelling-double", "pc-signal-temp", "pc-formula"] },
  { id: 24, tense: "present-final-test", type: "multiple_choice", question: "He ___ to the door to open it.", options: ["is running", "is runing", "is running", "is rnnning"], correctAnswer: "is running", explanation: "Run: краткий гласный + 1 согласная → удвоить n: running.", hintIds: ["pc-spelling-double", "pc-usage-now", "pc-formula"] },
  { id: 25, tense: "present-final-test", type: "multiple_choice", question: "She's ___ her English by watching films.", options: ["improving", "improveing", "improoving", "improvving"], correctAnswer: "improving", explanation: "Improve: два гласных перед v → НЕ удваиваем. Убираем e: improving.", hintIds: ["pc-spelling-drop-e", "pc-spelling-no-double", "pc-formula"] },

  // --- Special Cases ---
  { id: 26, tense: "present-final-test", type: "multiple_choice", question: "She ___ always ___ about something!", options: ["is / complaining", "complains", "has / complained", "was / complaining"], correctAnswer: "is / complaining", explanation: "Always + Present Continuous = раздражение / привычка, которая раздражает.", hintIds: ["pc-usage-irritate", "pc-formula"] },
  { id: 27, tense: "present-final-test", type: "multiple_choice", question: "___ you ever ___ sushi?", options: ["Have / tried", "Did / try", "Do / try", "Have / try"], correctAnswer: "Have / tried", explanation: "Ever + опыт жизни → Present Perfect: Have you ever + V3 (tried).", hintIds: ["pp-signal-ever-never", "pp-question", "pp-formula", "pp-irregular"] },
  { id: 28, tense: "present-final-test", type: "multiple_choice", question: "She ___ to the shop. She'll be back in 10 minutes.", options: ["has gone", "has been", "went", "has been going"], correctAnswer: "has gone", explanation: "Ушла и ещё не вернулась → has gone. Has been = уже вернулась.", hintIds: ["pp-been-gone", "pp-formula"] },
  { id: 29, tense: "present-final-test", type: "multiple_choice", question: "She ___ to Paris three times. She loves it there.", options: ["has been", "has gone", "went", "has been going"], correctAnswer: "has been", explanation: "Three times + любит (вернулась) → has been to. Has gone = ещё не вернулась.", hintIds: ["pp-been-gone", "pp-formula"] },
  { id: 30, tense: "present-final-test", type: "multiple_choice", question: "It ___ all day. The ground is completely wet.", options: ["has been raining", "has rained", "is raining", "rained"], correctAnswer: "has been raining", explanation: "All day + видимый результат (земля мокрая) → Present Perfect Continuous.", hintIds: ["ppc-signal-all", "ppc-usage-evidence", "ppc-formula"] },
  { id: 31, tense: "present-final-test", type: "multiple_choice", question: "I ___ five letters this morning.", options: ["have written", "wrote", "have been writing", "am writing"], correctAnswer: "have written", explanation: "This morning (период ещё не окончен) + конкретное количество (5) → Present Perfect.", hintIds: ["pp-signal-today", "pp-formula"] },
  { id: 32, tense: "present-final-test", type: "multiple_choice", question: "I ___ you are right, but I ___ about the details.", options: ["think / am thinking", "am thinking / think", "think / think", "am thinking / am thinking"], correctAnswer: "think / am thinking", explanation: "Think = мнение → Simple. About the details = размышляю (процесс) → Continuous.", hintIds: ["ps-think-opinion", "pc-dual-think"] },
  { id: 33, tense: "present-final-test", type: "multiple_choice", question: "How long ___ you ___ this jacket? — I ___ it for five years.", options: ["have / had / have had", "have / been having / have been having", "do / have / have", "have / had / had"], correctAnswer: "have / had / have had", explanation: "Have (владеть) = стативный → Present Perfect: have had. НЕ Continuous!", hintIds: ["pp-stative", "ppc-no-stative"] },
  { id: 34, tense: "present-final-test", type: "multiple_choice", question: "He ___ never ___ snails before.", options: ["has / tried", "has / been trying", "have / tried", "is / trying"], correctAnswer: "has / tried", explanation: "Never + опыт → Present Perfect: has + V3 (tried — неправильный).", hintIds: ["pp-signal-ever-never", "pp-formula", "pp-irregular"] },
  { id: 35, tense: "present-final-test", type: "multiple_choice", question: "If it ___ tomorrow, we ___ at home.", options: ["rains / will stay", "will rain / stay", "rains / stay", "will rain / will stay"], correctAnswer: "rains / stay", explanation: "If + придаточное → Present Simple (rains). Главная часть → will stay (First Conditional).", hintIds: ["ps-when-if"] },

  // ===== Fill in the Blank (36–65) =====

  // --- Mixed Tense Selection ---
  { id: 36, tense: "present-final-test", type: "fill_blank", question: "She ___ (go) to the gym every day, but this week she ___ (not / go) because she's ill.", correctAnswer: "goes / isn't going", explanation: "Every day → Present Simple (goes). This week = временная ситуация → Continuous (isn't going).", hintIds: ["ps-signal-routine", "pc-signal-temp", "ps-formula-vs", "pc-negative"] },
  { id: 37, tense: "present-final-test", type: "fill_blank", question: "I ___ (live) in London since 2015. I ___ (love) this city.", correctAnswer: "have lived / love", explanation: "Since + точка → Present Perfect (have lived). Love = стативный → Present Simple.", hintIds: ["pp-signal-since", "ps-stative"] },
  { id: 38, tense: "present-final-test", type: "fill_blank", question: "Look! The children ___ (play) in the garden. They ___ (play) there every afternoon.", correctAnswer: "are playing / play", explanation: "Look! = прямо сейчас → Continuous (are playing). Every afternoon = рутина → Simple (play).", hintIds: ["pc-signal-excl", "ps-signal-routine"] },
  { id: 39, tense: "present-final-test", type: "fill_blank", question: "He ___ (work) in this company for 10 years and he still ___ (enjoy) it.", correctAnswer: "has worked / enjoys", explanation: "For 10 лет → Present Perfect (has worked). Enjoys = стативный/привычка → Present Simple.", hintIds: ["pp-signal-for", "ps-stative", "pp-formula", "ps-formula-vs"] },
  { id: 40, tense: "present-final-test", type: "fill_blank", question: "She ___ (always / complain) about her job! It's so annoying.", correctAnswer: "is always complaining", explanation: "Always + Continuous = раздражение: is always complaining.", hintIds: ["pc-usage-irritate", "pc-formula"] },
  { id: 41, tense: "present-final-test", type: "fill_blank", question: "The film ___ (start) at 8 pm. We ___ (have) dinner before we go.", correctAnswer: "starts / are having", explanation: "Расписание → Present Simple (starts). Прямо сейчас/план → Continuous (are having).", hintIds: ["ps-schedule", "pc-usage-now", "ps-formula-v1", "pc-formula"] },
  { id: 42, tense: "present-final-test", type: "fill_blank", question: "I ___ (not / see) him recently. How long ___ (you / not / speak) to him?", correctAnswer: "haven't seen / haven't you spoken", explanation: "Recently → Present Perfect. How long → тоже Perfect: haven't you spoken.", hintIds: ["pp-signal-recently", "pp-negative", "pp-question", "pp-formula"] },
  { id: 43, tense: "present-final-test", type: "fill_blank", question: "When the train ___ (arrive), I ___ (call) you.", correctAnswer: "arrives / will call", explanation: "After when → Present Simple (arrives). Главная часть → will call.", hintIds: ["ps-when-if"] },
  { id: 44, tense: "present-final-test", type: "fill_blank", question: "She ___ (study) English for three years and she ___ (still / study) now.", correctAnswer: "has been studying / is still studying", explanation: "For 3 years + процесс → Present Perfect Continuous. Still + now → Present Continuous.", hintIds: ["ppc-signal-for", "ppc-usage-process", "pc-signal-now"] },
  { id: 45, tense: "present-final-test", type: "fill_blank", question: "This is the first time I ___ (eat) sushi. I ___ (never / try) it before.", correctAnswer: "have eaten / have never tried", explanation: "The first time + ever → Present Perfect. Never + before → Present Perfect.", hintIds: ["pp-signal-first-time", "pp-signal-ever-never", "pp-formula"] },

  // --- Stative Verbs ---
  { id: 46, tense: "present-final-test", type: "fill_blank", question: "I ___ (know) her for a long time. She ___ (be) very kind.", correctAnswer: "have known / is", explanation: "Know = стативный → Present Perfect (have known). Be = факт → Present Simple.", hintIds: ["pp-stative", "pp-signal-for"] },
  { id: 47, tense: "present-final-test", type: "fill_blank", question: "___ (you / understand) what I mean? I ___ (not / understand) this rule.", correctAnswer: "Do you understand / don't understand", explanation: "Understand = стативный → Present Simple для вопросов и отрицаний.", hintIds: ["ps-stative", "ps-question", "ps-negative"] },
  { id: 48, tense: "present-final-test", type: "fill_blank", question: "This ring ___ (belong) to my grandmother. It ___ (cost) a fortune.", correctAnswer: "belongs / costs", explanation: "Belong и cost = стативные глаголы → Present Simple.", hintIds: ["ps-stative", "ps-formula-vs"] },
  { id: 49, tense: "present-final-test", type: "fill_blank", question: "She ___ (feel) much better today. She ___ (not / feel) well yesterday.", correctAnswer: "is feeling / didn't feel", explanation: "Feel (самочувствие) → CAN use Continuous (is feeling). Yesterday → Past Simple.", hintIds: ["pc-dual-taste"] },
  { id: 50, tense: "present-final-test", type: "fill_blank", question: "I ___ (think) about changing my job. I ___ (want) something new.", correctAnswer: "am thinking / want", explanation: "Think (размышлять) → Continuous. Want = стативный → Simple.", hintIds: ["pc-dual-think", "ps-stative"] },
  { id: 51, tense: "present-final-test", type: "fill_blank", question: "The dinner ___ (smell) amazing! She ___ (smell) the sauce to check the salt.", correctAnswer: "smells / is smelling", explanation: "Smell (пахнет) = стативный → Simple. Smell (нюхает) = действие → Continuous.", hintIds: ["pc-dual-taste"] },
  { id: 52, tense: "present-final-test", type: "fill_blank", question: "We ___ (have) a great time at the party. I ___ (have) a new car now.", correctAnswer: "are having / have", explanation: "Have a great time (действие) → Continuous. Have a car (владение) = стативный → Simple.", hintIds: ["pc-dual-have"] },
  { id: 53, tense: "present-final-test", type: "fill_blank", question: "They ___ (not / agree) with us. They ___ (believe) we are wrong.", correctAnswer: "don't agree / believe", explanation: "Agree и believe = стативные глаголы → Present Simple.", hintIds: ["ps-stative", "ps-negative"] },
  { id: 54, tense: "present-final-test", type: "fill_blank", question: "She ___ (see) the doctor tomorrow at 3 pm. She ___ (see) what you mean.", correctAnswer: "is seeing / sees", explanation: "See = встречаться (запланировано) → Continuous. See = понимать → Simple (стативный).", hintIds: ["pc-dual-see", "pc-usage-planned"] },
  { id: 55, tense: "present-final-test", type: "fill_blank", question: "The soup ___ (taste) great. She ___ (taste) it to add more salt.", correctAnswer: "tastes / is tasting", explanation: "Taste (иметь вкус) = стативный → Simple. Taste (пробовать) = действие → Continuous.", hintIds: ["pc-dual-taste", "ps-stative", "pc-formula"] },

  // --- -ing Spelling + Combined ---
  { id: 56, tense: "present-final-test", type: "fill_blank", question: "She ___ (prefer) ___ (stay) at home tonight.", correctAnswer: "prefers / staying", explanation: "Prefer = стативный → Present Simple (prefers). After prefer → V-ing (staying).", hintIds: ["ps-stative", "ps-formula-vs"] },
  { id: 57, tense: "present-final-test", type: "fill_blank", question: "He ___ (lie) on the sofa and ___ (read) a book.", correctAnswer: "is lying / reading", explanation: "Lie → lying (ie→y+ing). Права сейчас → Continuous для обоих.", hintIds: ["pc-spelling-ie", "pc-formula"] },
  { id: 58, tense: "present-final-test", type: "fill_blank", question: "The children ___ (argue) about what to watch. They ___ (always / argue)!", correctAnswer: "are arguing / are always arguing", explanation: "Прямо сейчас → are arguing. Always + Continuous = раздражение.", hintIds: ["pc-usage-irritate", "pc-formula"] },
  { id: 59, tense: "present-final-test", type: "fill_blank", question: "I ___ (plan) ___ (travel) around Europe next summer.", correctAnswer: "am planning / to travel", explanation: "Plan = действие (процесс) → Continuous. After plan → to + V1 (to travel).", hintIds: ["pc-formula", "pc-usage-temporary"] },
  { id: 60, tense: "present-final-test", type: "fill_blank", question: "She ___ (practise) the piano since she was five. She ___ (practise) every day.", correctAnswer: "has been practising / practises", explanation: "Since + долгий процесс → Present Perfect Continuous. Британский: practising. Every day → Simple.", hintIds: ["ppc-signal-since", "ps-signal-routine", "ppc-formula", "ps-formula-vs"] },

  // --- gone vs been / just already yet ---
  { id: 61, tense: "present-final-test", type: "fill_blank", question: "She ___ (go) to the supermarket. She ___ (be) back in an hour.", correctAnswer: "has gone / will be", explanation: "Ушла и ещё не вернулась → has gone. Will be back = будущее.", hintIds: ["pp-been-gone"] },
  { id: 62, tense: "present-final-test", type: "fill_blank", question: "___ (you / already / finish) your homework? — No, I ___ (not / finish) yet.", correctAnswer: "Have you already finished / haven't finished", explanation: "Already + вопрос → Present Perfect. Yet + отрицание → Present Perfect.", hintIds: ["pp-signal-already", "pp-signal-yet", "pp-question"] },
  { id: 63, tense: "present-final-test", type: "fill_blank", question: "He ___ (just / get) a new job. He ___ (start) next Monday.", correctAnswer: "has just got / starts", explanation: "Just → Present Perfect. Британский: got (не gotten!). Starts = расписание → Present Simple.", hintIds: ["pp-signal-just", "ps-schedule"] },
  { id: 64, tense: "present-final-test", type: "fill_blank", question: "They ___ (be) to Japan twice. They ___ (go) there again next year.", correctAnswer: "have been / are going", explanation: "Twice = опыт → have been to (вернулись). Next year (план) → are going.", hintIds: ["pp-been-gone", "pc-usage-planned"] },
  { id: 65, tense: "present-final-test", type: "fill_blank", question: "I ___ (wait) for you for two hours! Where ___ (you / be)?", correctAnswer: "have been waiting / have you been", explanation: "For + ожидание → Present Perfect Continuous. Where have you been = Present Perfect.", hintIds: ["ppc-signal-for", "ppc-usage-process", "ppc-formula"] },

  // ===== Translate RU → EN (66–100) =====

  // --- Mixed Tense Selection ---
  { id: 66, tense: "present-final-test", type: "translate_ru_en", question: "Я знаю его с 2010 года.", correctAnswer: "I have known him since 2010", explanation: "Since + know (стативный) → Present Perfect: have known. НЕ Continuous!", hintIds: ["pp-stative", "pp-signal-since"] },
  { id: 67, tense: "present-final-test", type: "translate_ru_en", question: "Она обычно пьёт кофе, но сейчас пьёт чай.", correctAnswer: "She usually drinks coffee, but she is drinking tea now", explanation: "Обычно → Present Simple. Сейчас → Present Continuous.", hintIds: ["ps-signal-routine", "pc-signal-now", "ps-formula-vs", "pc-formula"] },
  { id: 68, tense: "present-final-test", type: "translate_ru_en", question: "Сколько времени ты учишь французский?", correctAnswer: "How long have you been learning French", explanation: "How long + процесс обучения → Present Perfect Continuous.", hintIds: ["ppc-usage-process", "ppc-formula"] },
  { id: 69, tense: "present-final-test", type: "translate_ru_en", question: "Когда я приеду, я позвоню тебе.", correctAnswer: "When I arrive, I will call you", explanation: "After when → Present Simple (arrive). Главная → will call. НЕ 'When I will arrive'!", hintIds: ["ps-when-if"] },
  { id: 70, tense: "present-final-test", type: "translate_ru_en", question: "Это лучший фильм, который я когда-либо видел.", correctAnswer: "This is the best film I have ever seen", explanation: "Superlative + ever → Present Perfect: have ever + V3 (seen).", hintIds: ["pp-signal-superlative", "pp-irregular"] },
  { id: 71, tense: "present-final-test", type: "translate_ru_en", question: "Она вечно жалуется! Это так раздражает.", correctAnswer: "She is always complaining! It's so annoying", explanation: "Always + Present Continuous = раздражение: is always complaining.", hintIds: ["pc-usage-irritate", "pc-formula"] },
  { id: 72, tense: "present-final-test", type: "translate_ru_en", question: "Премьер-министр подал в отставку вчера.", correctAnswer: "The Prime Minister resigned yesterday", explanation: "Yesterday = конкретное время → Past Simple: resigned. НЕ Present Perfect!", hintIds: ["pp-no-yesterday"] },
  { id: 73, tense: "present-final-test", type: "translate_ru_en", question: "Премьер-министр подал в отставку! (Свежая новость)", correctAnswer: "The Prime Minister has resigned", explanation: "Свежая новость без конкретного времени → Present Perfect: has resigned.", hintIds: ["pp-signal-news"] },
  { id: 74, tense: "present-final-test", type: "translate_ru_en", question: "Земля мокрая. Шёл дождь весь день.", correctAnswer: "The ground is wet. It has been raining all day", explanation: "All day + видимый результат (земля мокрая) → Present Perfect Continuous.", hintIds: ["ppc-signal-all", "ppc-usage-evidence", "ppc-formula"] },
  { id: 75, tense: "present-final-test", type: "translate_ru_en", question: "Я работаю в этом банке 5 лет.", correctAnswer: "I have worked in this bank for 5 years", explanation: "For 5 лет → Present Perfect (также допустим Continuous). Work = не стативный.", hintIds: ["pp-signal-for", "pp-formula"] },

  // --- Stative Verbs ---
  { id: 76, tense: "present-final-test", type: "translate_ru_en", question: "Мне кажется, ты прав, но я сейчас об этом думаю.", correctAnswer: "I think you are right, but I am thinking about it", explanation: "Think (мнение) → Simple. Think (размышлять) → Continuous.", hintIds: ["ps-think-opinion", "pc-dual-think", "pc-usage-now"] },
  { id: 77, tense: "present-final-test", type: "translate_ru_en", question: "Я не понимаю, что ты имеешь в виду.", correctAnswer: "I don't understand what you mean", explanation: "Understand и mean = стативные глаголы → Present Simple.", hintIds: ["ps-stative", "ps-negative"] },
  { id: 78, tense: "present-final-test", type: "translate_ru_en", question: "Этот суп вкусный. Она пробует его.", correctAnswer: "This soup tastes delicious. She is tasting it", explanation: "Taste (иметь вкус) → Simple. Taste (пробовать) → Continuous.", hintIds: ["pc-dual-taste"] },
  { id: 79, tense: "present-final-test", type: "translate_ru_en", question: "Она выглядит уставшей. Она всю неделю много работает.", correctAnswer: "She looks tired. She has been working a lot all week", explanation: "Look (выглядеть) = стативный → Simple. All week + процесс → Perfect Continuous.", hintIds: ["ps-stative", "ppc-signal-all", "ppc-usage-process"] },
  { id: 80, tense: "present-final-test", type: "translate_ru_en", question: "Я владею этой машиной 5 лет. Я не продаю её.", correctAnswer: "I have had this car for 5 years. I am not selling it", explanation: "Have (владеть) = стативный → Present Perfect: have had. НЕ have been having!", hintIds: ["ppc-no-stative", "pp-signal-for"] },
  { id: 81, tense: "present-final-test", type: "translate_ru_en", question: "Я встречаюсь с доктором завтра в 3 часа.", correctAnswer: "I am seeing the doctor tomorrow at 3 pm", explanation: "See = встречаться (запланировано) → Present Continuous: am seeing.", hintIds: ["pc-dual-see", "pc-usage-planned"] },
  { id: 82, tense: "present-final-test", type: "translate_ru_en", question: "Он не верит в призраков. Он считает это глупостью.", correctAnswer: "He doesn't believe in ghosts. He thinks it's silly", explanation: "Believe и think (мнение) = стативные → Present Simple.", hintIds: ["ps-stative", "ps-think-opinion", "ps-negative"] },
  { id: 83, tense: "present-final-test", type: "translate_ru_en", question: "Этот свитер стоит 50 фунтов. Он ей подходит.", correctAnswer: "This jumper costs \u00a350. It fits her", explanation: "Cost и fit = стативные глаголы → Present Simple. Британский: jumper.", hintIds: ["ps-stative", "ps-formula-vs"] },

  // --- -ing Rules ---
  { id: 84, tense: "present-final-test", type: "translate_ru_en", question: "Она лежит на кровати и читает.", correctAnswer: "She is lying in bed and reading", explanation: "Lie → lying (ie → y + ing). Права сейчас → Continuous.", hintIds: ["pc-spelling-ie", "pc-formula"] },
  { id: 85, tense: "present-final-test", type: "translate_ru_en", question: "Бегун бежит к финишу.", correctAnswer: "The runner is running to the finish line", explanation: "Run: краткий гласный + 1 согласная → удвоить n: running.", hintIds: ["pc-spelling-double", "pc-formula"] },
  { id: 86, tense: "present-final-test", type: "translate_ru_en", question: "Она готовит (cook) ужин на кухне.", correctAnswer: "She is cooking dinner in the kitchen", explanation: "Cook: два гласных (oo) → НЕ удваиваем: cooking.", hintIds: ["pc-spelling-no-double", "pc-formula"] },
  { id: 87, tense: "present-final-test", type: "translate_ru_en", question: "Мы путешествуем (travel) по Европе в этом месяце.", correctAnswer: "We are travelling around Europe this month", explanation: "Британский: travel → travelling (удвоение l). Временная ситуация → Continuous.", hintIds: ["pc-spelling-double", "pc-signal-temp", "pc-formula"] },
  { id: 88, tense: "present-final-test", type: "translate_ru_en", question: "Он снимает (take) фотографию прямо сейчас.", correctAnswer: "He is taking a photo right now", explanation: "Take: глагол на -e → убрать e, + -ing: taking.", hintIds: ["pc-spelling-drop-e", "pc-signal-now", "pc-formula"] },

  // --- Special Cases ---
  { id: 89, tense: "present-final-test", type: "translate_ru_en", question: "Поезд отправляется в 6 вечера. Он прибывает на платформу 3.", correctAnswer: "The train leaves at 6 pm. It is arriving at platform 3", explanation: "Расписание → Present Simple (leaves). Прямо сейчас → Continuous (is arriving).", hintIds: ["ps-schedule", "pc-usage-now", "ps-formula-v1", "pc-formula"] },
  { id: 90, tense: "present-final-test", type: "translate_ru_en", question: "Она только что получила новую работу.", correctAnswer: "She has just got a new job", explanation: "Just → Present Perfect. Британский: got (НЕ gotten!).", hintIds: ["pp-signal-just", "pp-formula"] },
  { id: 91, tense: "present-final-test", type: "translate_ru_en", question: "Если пойдёт дождь, мы останемся дома.", correctAnswer: "If it rains, we will stay home", explanation: "If + придаточное → Present Simple (rains). Главная → will stay.", hintIds: ["ps-when-if"] },
  { id: 92, tense: "present-final-test", type: "translate_ru_en", question: "Она уехала в магазин. Она вернётся через 10 минут.", correctAnswer: "She has gone to the shop. She will be back in 10 minutes", explanation: "Ушла и не вернулась → has gone (НЕ has been!).", hintIds: ["pp-been-gone"] },
  { id: 93, tense: "present-final-test", type: "translate_ru_en", question: "Она ездила в Париж три раза. Она любит этот город.", correctAnswer: "She has been to Paris three times. She loves the city", explanation: "Three times + любит (вернулась) → has been to. Love = стативный → Simple.", hintIds: ["pp-been-gone"] },
  { id: 94, tense: "present-final-test", type: "translate_ru_en", question: "Ты когда-нибудь был в Австралии? — Да, дважды.", correctAnswer: "Have you ever been to Australia? Yes, twice", explanation: "Ever → Present Perfect: Have you ever been to? Краткий ответ: Yes, twice.", hintIds: ["pp-signal-ever-never", "pp-been-gone"] },
  { id: 95, tense: "present-final-test", type: "translate_ru_en", question: "Я ещё не закончил проект.", correctAnswer: "I haven't finished the project yet", explanation: "Yet = ещё не → Present Perfect: haven't + V3 + yet.", hintIds: ["pp-signal-yet", "pp-negative"] },
  { id: 96, tense: "present-final-test", type: "translate_ru_en", question: "У меня есть собака. Я завёл её два года назад.", correctAnswer: "I have got a dog. I got it two years ago", explanation: "Британский: I've got. Two years ago = конкретное время → Past Simple: got.", hintIds: ["ps-have-got", "pp-no-yesterday"] },
  { id: 97, tense: "present-final-test", type: "translate_ru_en", question: "Мы летим в Нью-Йорк на следующей неделе.", correctAnswer: "We are flying to New York next week", explanation: "Запланированное будущее → Present Continuous: are flying.", hintIds: ["pc-usage-planned", "pc-formula"] },
  { id: 98, tense: "present-final-test", type: "translate_ru_en", question: "Я пишу письмо другу уже два часа.", correctAnswer: "I have been writing a letter to my friend for two hours", explanation: "For + процесс письма → Present Perfect Continuous: have been writing.", hintIds: ["ppc-signal-for", "ppc-usage-process", "ppc-formula"] },
  { id: 99, tense: "present-final-test", type: "translate_ru_en", question: "Она не звонила мне на этой неделе.", correctAnswer: "She hasn't called me this week", explanation: "This week (период не окончен) + отрицание → hasn't + V3.", hintIds: ["pp-signal-today", "pp-negative"] },
  { id: 100, tense: "present-final-test", type: "translate_ru_en", question: "Мой английский улучшается. Я занимаюсь каждый день.", correctAnswer: "My English is getting better. I study every day", explanation: "Изменение → Continuous (is getting). Каждый день = рутина → Simple (study).", hintIds: ["pc-usage-change", "ps-signal-routine", "pc-formula", "ps-formula-v1"] },
];
